/*******************************************************************************
 * Copyright (c) 2025 Obeo.
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *     Obeo - initial API and implementation
 *******************************************************************************/

package org.eclipse.sirius.components.papaya.provider.spec;

import org.eclipse.emf.common.notify.AdapterFactory;
import org.eclipse.emf.edit.provider.StyledString;
import org.eclipse.sirius.components.papaya.ContainingLink;
import org.eclipse.sirius.components.papaya.NamedElement;
import org.eclipse.sirius.components.papaya.provider.ContainingLinkItemProvider;

/**
 * Customization of the item provider implementation generated by EMF.
 *
 * @author sbegaudeau
 */
public class ContainingLinkItemProviderSpec extends ContainingLinkItemProvider {
    public ContainingLinkItemProviderSpec(AdapterFactory adapterFactory) {
        super(adapterFactory);
    }

    @Override
    public Object getImage(Object object) {
        return this.overlayImage(object, this.getResourceLocator().getImage("papaya/full/obj16/ContainingLink.svg"));
    }

    @Override
    public Object getStyledText(Object object) {
        if (object instanceof ContainingLink containingLink) {
            StyledString styledLabel = new StyledString();
            if (containingLink.getTarget() instanceof NamedElement namedElement && namedElement.getName() != null && !namedElement.getName().isEmpty()) {
                styledLabel.append(containingLink.getKind());
                styledLabel.append(" ");
                styledLabel.append(namedElement.getName());
            } else {
                styledLabel.append(this.getString("_UI_ContainingLink_type"));
            }
            return styledLabel;
        }
        return super.getStyledText(object);
    }
}
