/*******************************************************************************
 * Copyright (c) 2026 Obeo.
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *     Obeo - initial API and implementation
 *******************************************************************************/

package org.eclipse.sirius.components.papaya.provider.spec;

import java.util.List;

import org.eclipse.emf.common.notify.AdapterFactory;
import org.eclipse.emf.edit.provider.ComposedImage;
import org.eclipse.sirius.components.papaya.DataType;
import org.eclipse.sirius.components.papaya.provider.DependencyLinkItemProvider;
import org.eclipse.sirius.components.papaya.provider.spec.images.VisibilityOverlayImageProvider;
import org.eclipse.sirius.components.papaya.provider.spec.label.NamedElementStyledTextProvider;

/**
 * Customization of the item provider implementation generated by EMF.
 *
 * @author ncouvert
 */
public class DependencyLinkItemProviderSpec extends DependencyLinkItemProvider {
    public DependencyLinkItemProviderSpec(AdapterFactory adapterFactory) {
        super(adapterFactory);
    }

    @Override
    public Object getImage(Object object) {
        if (object instanceof DataType dataType) {
            var visibilityImage = new VisibilityOverlayImageProvider().overlayImage(this.getResourceLocator(), dataType.getVisibility());

            return new ComposedImage(List.of(
                    this.getResourceLocator().getImage("papaya/full/obj16/DependencyLink.svg"),
                    visibilityImage
            ));
        }
        return this.overlayImage(object, this.getResourceLocator().getImage("papaya/full/obj16/DependencyLink.svg"));
    }

    @Override
    public Object getStyledText(Object object) {
        if (object instanceof DataType dataType) {
            return new NamedElementStyledTextProvider().getStyledText(dataType, this.getString("_UI_DependencyLink_type"));
        }
        return super.getStyledText(object);
    }
}
