/*******************************************************************************
 * Copyright (c) 2025 Obeo.
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *     Obeo - initial API and implementation
 *******************************************************************************/
package org.eclipse.sirius.components.papaya.provider.spec;

import org.eclipse.emf.common.notify.AdapterFactory;
import org.eclipse.emf.edit.provider.StyledString;
import org.eclipse.sirius.components.papaya.Domain;
import org.eclipse.sirius.components.papaya.provider.DomainItemProvider;

/**
 * Customization of the item provider implementation generated by EMF.
 *
 * @author sbegaudeau
 */
public class DomainItemProviderSpec extends DomainItemProvider {
    public DomainItemProviderSpec(AdapterFactory adapterFactory) {
        super(adapterFactory);
    }

    @Override
    public Object getImage(Object object) {
        return this.overlayImage(object, this.getResourceLocator().getImage("papaya/full/obj16/Domain.svg"));
    }



    @Override
    public Object getStyledText(Object object) {
        if (object instanceof Domain domain) {
            StyledString styledLabel = new StyledString();
            if (domain.getName().isEmpty()) {
                styledLabel.append(this.getString("_UI_Domain_type"));
            } else {
                styledLabel.append(domain.getName());
            }
            return styledLabel;
        }
        return super.getStyledText(object);
    }
}
