/*******************************************************************************
 * Copyright (c) 2024 Obeo.
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *     Obeo - initial API and implementation
 *******************************************************************************/
package org.eclipse.sirius.components.papaya.provider.spec;

import java.util.Optional;

import org.eclipse.emf.common.notify.AdapterFactory;
import org.eclipse.emf.edit.provider.StyledString;
import org.eclipse.sirius.components.papaya.GenericType;
import org.eclipse.sirius.components.papaya.Type;
import org.eclipse.sirius.components.papaya.provider.GenericTypeItemProvider;

/**
 * Customization of the item provider implementation generated by EMF.
 *
 * @author sbegaudeau
 */
public class GenericTypeItemProviderSpec extends GenericTypeItemProvider {
    public GenericTypeItemProviderSpec(AdapterFactory adapterFactory) {
        super(adapterFactory);
    }

    @Override
    public Object getImage(Object object) {
        return this.overlayImage(object, this.getResourceLocator().getImage("full/obj16/GenericType.svg"));
    }

    @Override
    public Object getStyledText(Object object) {
        if (object instanceof GenericType genericType) {
            StyledString styledLabel = new StyledString();

            var text = Optional.ofNullable(genericType.getRawType()).map(Type::getName).orElse("");
            styledLabel.append(text);

            if (!genericType.getTypeArguments().isEmpty()) {
                styledLabel.append("<", PapayaStyledStringStyles.DECORATOR_STYLE);

                for (var i = 0; i < genericType.getTypeArguments().size(); i++) {
                    var typeParameter = genericType.getTypeArguments().get(i);
                    var typeArgumentLabel = this.getStyledText(typeParameter);
                    if (typeArgumentLabel instanceof StyledString styledString) {
                        styledLabel.append(styledString);

                        if (i < genericType.getTypeArguments().size() - 1) {
                            styledLabel.append(", ", PapayaStyledStringStyles.DECORATOR_STYLE);
                        }
                    }
                }

                styledLabel.append(">", PapayaStyledStringStyles.DECORATOR_STYLE);
            }
            return styledLabel;
        }
        return super.getStyledText(object);
    }
}
