/*******************************************************************************
 * Copyright (c) 2024, 2025 Obeo.
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *     Obeo - initial API and implementation
 *******************************************************************************/
package org.eclipse.sirius.components.papaya.provider.spec;

import java.util.List;

import org.eclipse.emf.common.notify.AdapterFactory;
import org.eclipse.emf.edit.provider.ComposedImage;
import org.eclipse.emf.edit.provider.StyledString;
import org.eclipse.sirius.components.papaya.Interface;
import org.eclipse.sirius.components.papaya.provider.InterfaceItemProvider;
import org.eclipse.sirius.components.papaya.provider.spec.images.VisibilityOverlayImageProvider;

/**
 * Customization of the item provider implementation generated by EMF.
 *
 * @author sbegaudeau
 */
public class InterfaceItemProviderSpec extends InterfaceItemProvider {
    public InterfaceItemProviderSpec(AdapterFactory adapterFactory) {
        super(adapterFactory);
    }

    @Override
    public Object getImage(Object object) {
        if (object instanceof Interface anInterface) {
            var visibilityImage = new VisibilityOverlayImageProvider().overlayImage(this.getResourceLocator(), anInterface.getVisibility());

            return new ComposedImage(List.of(
                    this.getResourceLocator().getImage("papaya/full/obj16/Interface.svg"),
                    visibilityImage
            ));
        }
        return this.overlayImage(object, this.getResourceLocator().getImage("papaya/full/obj16/Interface.svg"));
    }

    @Override
    public Object getStyledText(Object object) {
        if (object instanceof Interface anInterface && anInterface.getName() != null && !anInterface.getName().isBlank()) {
            StyledString styledLabel = new StyledString();
            styledLabel.append(anInterface.getName());

            if (!anInterface.getTypeParameters().isEmpty()) {
                styledLabel.append("<", PapayaStyledStringStyles.DECORATOR_STYLE);

                for (var i = 0; i < anInterface.getTypeParameters().size(); i++) {
                    var typeParameter = anInterface.getTypeParameters().get(i);
                    styledLabel.append(typeParameter.getName(), PapayaStyledStringStyles.GENERIC_TYPE_STYLE);
                    if (i < anInterface.getTypeParameters().size() - 1) {
                        styledLabel.append(", ", PapayaStyledStringStyles.DECORATOR_STYLE);
                    }
                }

                styledLabel.append(">", PapayaStyledStringStyles.DECORATOR_STYLE);
            }
            return styledLabel;
        }
        return super.getStyledText(object);
    }
}
