/*******************************************************************************
 * Copyright (c) 2024 Obeo.
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *     Obeo - initial API and implementation
 *******************************************************************************/
package org.eclipse.sirius.components.papaya.provider.spec;

import java.util.List;
import java.util.stream.Collectors;

import org.eclipse.emf.common.notify.AdapterFactory;
import org.eclipse.emf.edit.provider.ComposedImage;
import org.eclipse.sirius.components.papaya.Interface;
import org.eclipse.sirius.components.papaya.TypeParameter;
import org.eclipse.sirius.components.papaya.provider.InterfaceItemProvider;
import org.eclipse.sirius.components.papaya.provider.spec.images.VisibilityOverlayImageProvider;

/**
 * Customization of the item provider implementation generated by EMF.
 *
 * @author sbegaudeau
 */
public class InterfaceItemProviderSpec extends InterfaceItemProvider {
    public InterfaceItemProviderSpec(AdapterFactory adapterFactory) {
        super(adapterFactory);
    }

    @Override
    public Object getImage(Object object) {
        if (object instanceof Interface anInterface) {
            var visibilityImage = new VisibilityOverlayImageProvider().overlayImage(this.getResourceLocator(), anInterface.getVisibility());

            return new ComposedImage(List.of(
                    this.getResourceLocator().getImage("full/obj16/Interface.svg"),
                    visibilityImage
            ));
        }
        return this.overlayImage(object, this.getResourceLocator().getImage("full/obj16/Interface.svg"));
    }

    @Override
    public String getText(Object object) {
        var text = this.getString("_UI_Interface_type");
        if (object instanceof Interface anInterface) {
            if (anInterface.getName() != null && !anInterface.getName().isBlank()) {
                var typeParameters = "";
                if (!anInterface.getTypeParameters().isEmpty()) {
                    typeParameters = anInterface.getTypeParameters()
                            .stream()
                            .map(TypeParameter::getName)
                            .collect(Collectors.joining(", ", "<", ">"));
                }
                text = anInterface.getName() + typeParameters;
            }
        }
        return text;
    }
}
