/*******************************************************************************
 * Copyright (c) 2024 Obeo.
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *     Obeo - initial API and implementation
 *******************************************************************************/
package org.eclipse.sirius.components.papaya.provider.spec;

import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;

import org.eclipse.emf.common.notify.AdapterFactory;
import org.eclipse.emf.edit.provider.ComposedImage;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.sirius.components.papaya.Operation;
import org.eclipse.sirius.components.papaya.provider.OperationItemProvider;
import org.eclipse.sirius.components.papaya.provider.PapayaItemProviderAdapterFactory;
import org.eclipse.sirius.components.papaya.provider.spec.images.VisibilityOverlayImageProvider;

/**
 * Customization of the item provider implementation generated by EMF.
 *
 * @author sbegaudeau
 */
public class OperationItemProviderSpec extends OperationItemProvider {
    public OperationItemProviderSpec(AdapterFactory adapterFactory) {
        super(adapterFactory);
    }

    @Override
    public Object getImage(Object object) {
        if (object instanceof Operation operation) {
            var visibilityImage = new VisibilityOverlayImageProvider().overlayImage(this.getResourceLocator(), operation.getVisibility());

            return new ComposedImage(List.of(
                    this.getResourceLocator().getImage("full/obj16/Operation.svg"),
                    visibilityImage
            ));
        }
        return this.overlayImage(object, this.getResourceLocator().getImage("full/obj16/Operation.svg"));
    }

    @Override
    public String getText(Object object) {
        if (object instanceof Operation operation && operation.getName() != null && !operation.getName().isBlank()) {
            var text = operation.getName();

            var parameters = operation.getParameters().stream()
                    .map(parameter -> Optional.ofNullable(new PapayaItemProviderAdapterFactory().adapt(parameter, IItemLabelProvider.class))
                            .filter(IItemLabelProvider.class::isInstance)
                            .map(IItemLabelProvider.class::cast)
                            .map(itemLabelProvider -> itemLabelProvider.getText(parameter))
                            .orElse("")
                    )
                    .collect(Collectors.joining(", ", "(", ")"));

            var type = "";
            if (operation.getType() != null) {
                var adapter = new PapayaItemProviderAdapterFactory().adapt(operation.getType(), IItemLabelProvider.class);
                if (adapter instanceof IItemLabelProvider itemLabelProvider) {
                    type = ": " + itemLabelProvider.getText(operation.getType());
                }
            }

            return text + parameters + type;
        }
        return super.getText(object);
    }
}
