/*******************************************************************************
 * Copyright (c) 2024 Obeo.
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *     Obeo - initial API and implementation
 *******************************************************************************/
package org.eclipse.sirius.components.papaya.provider.spec;

import org.eclipse.emf.common.notify.AdapterFactory;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.sirius.components.papaya.Parameter;
import org.eclipse.sirius.components.papaya.provider.PapayaItemProviderAdapterFactory;
import org.eclipse.sirius.components.papaya.provider.ParameterItemProvider;

/**
 * Customization of the item provider implementation generated by EMF.
 *
 * @author sbegaudeau
 */
public class ParameterItemProviderSpec extends ParameterItemProvider {
    public ParameterItemProviderSpec(AdapterFactory adapterFactory) {
        super(adapterFactory);
    }

    @Override
    public Object getImage(Object object) {
        return this.overlayImage(object, this.getResourceLocator().getImage("full/obj16/Parameter.svg"));
    }

    @Override
    public String getText(Object object) {
        if (object instanceof Parameter parameter && parameter.getName() != null && !parameter.getName().isBlank()) {
            var text = parameter.getName();

            if (parameter.getType() != null) {
                var adapter = new PapayaItemProviderAdapterFactory().adapt(parameter.getType(), IItemLabelProvider.class);
                if (adapter instanceof IItemLabelProvider itemLabelProvider) {
                    text = text + ": " + itemLabelProvider.getText(parameter.getType());
                }
            }

            return text;
        }
        return super.getText(object);
    }
}
