/*******************************************************************************
 * Copyright (c) 2025 Obeo.
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *     Obeo - initial API and implementation
 *******************************************************************************/
package org.eclipse.sirius.components.papaya.provider.spec;

import java.util.Optional;

import org.eclipse.emf.common.notify.AdapterFactory;
import org.eclipse.emf.edit.provider.StyledString;
import org.eclipse.sirius.components.papaya.Channel;
import org.eclipse.sirius.components.papaya.Message;
import org.eclipse.sirius.components.papaya.Publication;
import org.eclipse.sirius.components.papaya.provider.PublicationItemProvider;

/**
 * Customization of the item provider implementation generated by EMF.
 *
 * @author sbegaudeau
 */
public class PublicationItemProviderSpec extends PublicationItemProvider {
    public PublicationItemProviderSpec(AdapterFactory adapterFactory) {
        super(adapterFactory);
    }

    @Override
    public Object getImage(Object object) {
        return this.overlayImage(object, this.getResourceLocator().getImage("papaya/full/obj16/Publication.svg"));
    }

    @Override
    public Object getStyledText(Object object) {
        if (object instanceof Publication publication) {
            StyledString styledLabel = new StyledString();
            styledLabel.append(Optional.ofNullable(publication.getMessage()).map(Message::getName).orElse("null"));
            styledLabel.append(" over ");
            styledLabel.append(Optional.ofNullable(publication.getChannel()).map(Channel::getName).orElse("null"));
            return styledLabel;
        }
        return super.getStyledText(object);
    }
}
