/*******************************************************************************
 * Copyright (c) 2026 Obeo.
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *     Obeo - initial API and implementation
 *******************************************************************************/
package org.eclipse.sirius.components.view.form.provider.spec;

import java.util.Collection;

import org.eclipse.emf.common.notify.AdapterFactory;
import org.eclipse.sirius.components.view.form.BarChartDescription;
import org.eclipse.sirius.components.view.form.ButtonDescription;
import org.eclipse.sirius.components.view.form.CheckboxDescription;
import org.eclipse.sirius.components.view.form.DateTimeDescription;
import org.eclipse.sirius.components.view.form.FlexDirection;
import org.eclipse.sirius.components.view.form.FlexboxContainerDescription;
import org.eclipse.sirius.components.view.form.FormFactory;
import org.eclipse.sirius.components.view.form.FormPackage;
import org.eclipse.sirius.components.view.form.ImageDescription;
import org.eclipse.sirius.components.view.form.LabelDescription;
import org.eclipse.sirius.components.view.form.LinkDescription;
import org.eclipse.sirius.components.view.form.ListDescription;
import org.eclipse.sirius.components.view.form.MultiSelectDescription;
import org.eclipse.sirius.components.view.form.PieChartDescription;
import org.eclipse.sirius.components.view.form.RadioDescription;
import org.eclipse.sirius.components.view.form.RichTextDescription;
import org.eclipse.sirius.components.view.form.SelectDescription;
import org.eclipse.sirius.components.view.form.SliderDescription;
import org.eclipse.sirius.components.view.form.TextAreaDescription;
import org.eclipse.sirius.components.view.form.TextfieldDescription;
import org.eclipse.sirius.components.view.form.provider.FlexboxContainerDescriptionItemProvider;

/** Customization of the item provider implementation generated by EMF. */ public class FlexboxContainerDescriptionItemProviderSpec extends FlexboxContainerDescriptionItemProvider {     public FlexboxContainerDescriptionItemProviderSpec(AdapterFactory adapterFactory) {         super(adapterFactory);     }
    @Override
    public Object getImage(Object object) {
        if (object instanceof FlexboxContainerDescription && FlexDirection.ROW.equals(((FlexboxContainerDescription) object).getFlexDirection())) {
            return this.overlayImage(object, this.getResourceLocator().getImage("full/obj16/FlexboxContainerDescription_Row.svg"));
        }
        return this.overlayImage(object, this.getResourceLocator().getImage("full/obj16/FlexboxContainerDescription_Column.svg"));
    }

    @Override
    protected void collectNewChildDescriptors(Collection<Object> newChildDescriptors, Object object) {
        super.collectNewChildDescriptors(newChildDescriptors, object);

        newChildDescriptors.add(this.createChildParameter(FormPackage.Literals.FLEXBOX_CONTAINER_DESCRIPTION__CHILDREN, FormFactory.eINSTANCE.createFormElementFor()));
        newChildDescriptors.add(this.createChildParameter(FormPackage.Literals.FLEXBOX_CONTAINER_DESCRIPTION__CHILDREN, FormFactory.eINSTANCE.createFormElementIf()));

        BarChartDescription barChartDescription = FormFactory.eINSTANCE.createBarChartDescription();
        barChartDescription.setStyle(FormFactory.eINSTANCE.createBarChartDescriptionStyle());
        newChildDescriptors.add(this.createChildParameter(FormPackage.Literals.FLEXBOX_CONTAINER_DESCRIPTION__CHILDREN, barChartDescription));

        ButtonDescription buttonDescription = FormFactory.eINSTANCE.createButtonDescription();
        buttonDescription.setStyle(FormFactory.eINSTANCE.createButtonDescriptionStyle());
        newChildDescriptors.add(this.createChildParameter(FormPackage.Literals.FLEXBOX_CONTAINER_DESCRIPTION__CHILDREN, buttonDescription));

        CheckboxDescription checkboxDescription = FormFactory.eINSTANCE.createCheckboxDescription();
        checkboxDescription.setStyle(FormFactory.eINSTANCE.createCheckboxDescriptionStyle());
        newChildDescriptors.add(this.createChildParameter(FormPackage.Literals.FLEXBOX_CONTAINER_DESCRIPTION__CHILDREN, checkboxDescription));

        DateTimeDescription dateTimeDescription = FormFactory.eINSTANCE.createDateTimeDescription();
        dateTimeDescription.setStyle(FormFactory.eINSTANCE.createDateTimeDescriptionStyle());
        newChildDescriptors.add(this.createChildParameter(FormPackage.Literals.FLEXBOX_CONTAINER_DESCRIPTION__CHILDREN, dateTimeDescription));

        FlexboxContainerDescription flexboxContainerDescription = FormFactory.eINSTANCE.createFlexboxContainerDescription();
        newChildDescriptors.add(this.createChildParameter(FormPackage.Literals.FLEXBOX_CONTAINER_DESCRIPTION__CHILDREN, flexboxContainerDescription));

        ImageDescription imageDescription = FormFactory.eINSTANCE.createImageDescription();
        newChildDescriptors.add(this.createChildParameter(FormPackage.Literals.FLEXBOX_CONTAINER_DESCRIPTION__CHILDREN, imageDescription));

        LabelDescription labelDescription = FormFactory.eINSTANCE.createLabelDescription();
        labelDescription.setStyle(FormFactory.eINSTANCE.createLabelDescriptionStyle());
        newChildDescriptors.add(this.createChildParameter(FormPackage.Literals.FLEXBOX_CONTAINER_DESCRIPTION__CHILDREN, labelDescription));

        LinkDescription linkDescription = FormFactory.eINSTANCE.createLinkDescription();
        linkDescription.setStyle(FormFactory.eINSTANCE.createLinkDescriptionStyle());
        newChildDescriptors.add(this.createChildParameter(FormPackage.Literals.FLEXBOX_CONTAINER_DESCRIPTION__CHILDREN, linkDescription));

        ListDescription listDescription = FormFactory.eINSTANCE.createListDescription();
        listDescription.setStyle(FormFactory.eINSTANCE.createListDescriptionStyle());
        newChildDescriptors.add(this.createChildParameter(FormPackage.Literals.FLEXBOX_CONTAINER_DESCRIPTION__CHILDREN, listDescription));

        MultiSelectDescription multiSelectDescription = FormFactory.eINSTANCE.createMultiSelectDescription();
        multiSelectDescription.setStyle(FormFactory.eINSTANCE.createMultiSelectDescriptionStyle());
        newChildDescriptors.add(this.createChildParameter(FormPackage.Literals.FLEXBOX_CONTAINER_DESCRIPTION__CHILDREN, multiSelectDescription));

        PieChartDescription pieChartDescription = FormFactory.eINSTANCE.createPieChartDescription();
        pieChartDescription.setStyle(FormFactory.eINSTANCE.createPieChartDescriptionStyle());
        newChildDescriptors.add(this.createChildParameter(FormPackage.Literals.FLEXBOX_CONTAINER_DESCRIPTION__CHILDREN, pieChartDescription));

        RadioDescription radioDescription = FormFactory.eINSTANCE.createRadioDescription();
        radioDescription.setStyle(FormFactory.eINSTANCE.createRadioDescriptionStyle());
        newChildDescriptors.add(this.createChildParameter(FormPackage.Literals.FLEXBOX_CONTAINER_DESCRIPTION__CHILDREN, radioDescription));

        RichTextDescription richTextDescription = FormFactory.eINSTANCE.createRichTextDescription();
        newChildDescriptors.add(this.createChildParameter(FormPackage.Literals.FLEXBOX_CONTAINER_DESCRIPTION__CHILDREN, richTextDescription));

        SelectDescription selectDescription = FormFactory.eINSTANCE.createSelectDescription();
        selectDescription.setStyle(FormFactory.eINSTANCE.createSelectDescriptionStyle());
        newChildDescriptors.add(this.createChildParameter(FormPackage.Literals.FLEXBOX_CONTAINER_DESCRIPTION__CHILDREN, selectDescription));

        SliderDescription sliderDescription = FormFactory.eINSTANCE.createSliderDescription();
        newChildDescriptors.add(this.createChildParameter(FormPackage.Literals.FLEXBOX_CONTAINER_DESCRIPTION__CHILDREN, sliderDescription));

        newChildDescriptors.add(this.createChildParameter(FormPackage.Literals.FLEXBOX_CONTAINER_DESCRIPTION__CHILDREN, FormFactory.eINSTANCE.createSplitButtonDescription()));

        TextAreaDescription textareaDescription = FormFactory.eINSTANCE.createTextAreaDescription();
        textareaDescription.setStyle(FormFactory.eINSTANCE.createTextareaDescriptionStyle());
        newChildDescriptors.add(this.createChildParameter(FormPackage.Literals.FLEXBOX_CONTAINER_DESCRIPTION__CHILDREN, textareaDescription));

        TextfieldDescription textfieldDescription = FormFactory.eINSTANCE.createTextfieldDescription();
        textfieldDescription.setStyle(FormFactory.eINSTANCE.createTextfieldDescriptionStyle());
        newChildDescriptors.add(this.createChildParameter(FormPackage.Literals.FLEXBOX_CONTAINER_DESCRIPTION__CHILDREN, textfieldDescription));

        newChildDescriptors.add(this.createChildParameter(FormPackage.Literals.FLEXBOX_CONTAINER_DESCRIPTION__CHILDREN, FormFactory.eINSTANCE.createTreeDescription()));

        newChildDescriptors.add(this.createChildParameter(FormPackage.Literals.FLEXBOX_CONTAINER_DESCRIPTION__BORDER_STYLE, FormFactory.eINSTANCE.createContainerBorderStyle()));

        newChildDescriptors
                .add(this.createChildParameter(FormPackage.Literals.FLEXBOX_CONTAINER_DESCRIPTION__CONDITIONAL_BORDER_STYLES, FormFactory.eINSTANCE.createConditionalContainerBorderStyle()));
    }

}
