/*******************************************************************************
 * Copyright (c) 2026 Obeo.
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *     Obeo - initial API and implementation
 *******************************************************************************/
package org.eclipse.sirius.components.view.form.provider.spec;

import java.util.Collection;

import org.eclipse.emf.common.notify.AdapterFactory;
import org.eclipse.sirius.components.view.form.FormFactory;
import org.eclipse.sirius.components.view.form.FormPackage;
import org.eclipse.sirius.components.view.form.FormVariable;
import org.eclipse.sirius.components.view.form.GroupDescription;
import org.eclipse.sirius.components.view.form.PageDescription;
import org.eclipse.sirius.components.view.form.provider.FormDescriptionItemProvider;

/** Customization of the item provider implementation generated by EMF. */ public class FormDescriptionItemProviderSpec extends FormDescriptionItemProvider {     public FormDescriptionItemProviderSpec(AdapterFactory adapterFactory) {         super(adapterFactory);     }
    @Override
    public Object getImage(Object object) {
        return this.overlayImage(object, this.getResourceLocator().getImage("full/obj16/FormDescription.svg"));
    }

    @Override
    protected void collectNewChildDescriptors(Collection<Object> newChildDescriptors, Object object) {
        super.collectNewChildDescriptors(newChildDescriptors, object);

        PageDescription pageDescription = FormFactory.eINSTANCE.createPageDescription();
        FormVariable formVariable = FormFactory.eINSTANCE.createFormVariable();
        GroupDescription groupDescription = FormFactory.eINSTANCE.createGroupDescription();
        pageDescription.getGroups().add(groupDescription);
        newChildDescriptors.add(this.createChildParameter(FormPackage.Literals.FORM_DESCRIPTION__PAGES, pageDescription));
        newChildDescriptors.add(this.createChildParameter(FormPackage.Literals.FORM_DESCRIPTION__FORM_VARIABLES, formVariable));
    }

}
