/*******************************************************************************
 * Copyright (c) 2026 Obeo.
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *     Obeo - initial API and implementation
 *******************************************************************************/
package org.eclipse.sirius.components.view.form.provider.spec;

import java.util.Collection;

import org.eclipse.emf.common.notify.AdapterFactory;
import org.eclipse.sirius.components.view.form.ButtonDescription;
import org.eclipse.sirius.components.view.form.FormFactory;
import org.eclipse.sirius.components.view.form.FormPackage;
import org.eclipse.sirius.components.view.form.provider.PageDescriptionItemProvider;

/**
 * Customization of the item provider implementation generated by EMF.
 *
 * @author lfasani
 */
public class PageDescriptionItemProviderSpec extends PageDescriptionItemProvider {
    public PageDescriptionItemProviderSpec(AdapterFactory adapterFactory) {
        super(adapterFactory);
    }

    @Override
    public Object getImage(Object object) {
        return this.overlayImage(object, this.getResourceLocator().getImage("full/obj16/PageDescription.svg"));
    }

    @Override
    protected void collectNewChildDescriptors(Collection<Object> newChildDescriptors, Object object) {
        newChildDescriptors.add(this.createChildParameter(FormPackage.Literals.PAGE_DESCRIPTION__GROUPS, FormFactory.eINSTANCE.createGroupDescription()));

        ButtonDescription toolbarActionDescription = FormFactory.eINSTANCE.createButtonDescription();
        toolbarActionDescription.setStyle(FormFactory.eINSTANCE.createButtonDescriptionStyle());
        toolbarActionDescription.setName("ToolbarAction");
        newChildDescriptors.add(this.createChildParameter(FormPackage.Literals.PAGE_DESCRIPTION__TOOLBAR_ACTIONS, toolbarActionDescription));
    }

}
