= For Studio Developers

== General

.I want the in-line label edition of a Node to allow editing attribute values.
[%collapsible]
====
In the _Edit Label_ of your _Node Description_, set the _Expression_ to call a custom service
====

.How can I programmatically access the contents of a diagram, from the backend?
[%collapsible]
====
#TODO: Equivalent to retrieving the `DSemanticDiagram`.#
[source,java]
----
return "TODO";
----
====


.Can I use another IDE than what is recommended in the xref:developer-guide:setup/instructions.adoc[Development Guide setup instructions]?
[%collapsible]
====
Yes. There are no hard dependencies from {sw} to the IDE used for editing the backend or the frontend.
====

.Is {sw} based on the https://eclipse.dev/glsp/[Graphical Language Server Platform (GLSP)]?
[%collapsible]
====
No. GLSP was made for _diagram representations_, while {sw} supports several very different types of graphical representations. xref:user-manual:studio-runtime/representation-editors/diagram.adoc[Diagram Representations] are only one such type of graphical representation. Other types of representations, such as xref:user-manual:studio-runtime/representation-editors/tree.adoc[Tree Representations] or xref:user-manual:studio-runtime/representation-editors/form.adoc[Form Representations] cannot be supported by GLSP.
====

.In the backend, how I can override core services?
[%collapsible]
====
#TODO: talk about how with Spring it is easy to redefine and contribute core services. Using `@Primary` and `@Order` annotations.#
====

#TODO: Add cookbook entry to sort-of "serialize" a programmatically-created studio definition so that it can be explored as a View model.#

== Logging

.In the backend, how can I log the time taken for rendering a Diagram representation?
[%collapsible]
====
In `sirius-web-sample-application/src/main/resources/application-dev.properties`, set `logging.level.org.eclipse.sirius.components.collaborative.diagrams.DiagramCreationService=trace`.
====

== Debugging

.In the backend, how can I debug what happens for a `Palette`?
[%collapsible]
====
Set a breakpoint at `org.eclipse.sirius.components.collaborative.diagrams.handlers.GetPaletteEventHandler.handle(One<IPayload>, Many<ChangeDescription>, IEditingContext, IDiagramContext, IDiagramInput)`.
====

.How can I enable the `Debug` view used to get internal information about a diagram?
[%collapsible]
====
In the sources of the backend, edit file _application-dev.properties_ to add `sirius.components.diagram.debug=true`.
====