/*******************************************************************************
 * Copyright (c) 2019, 2020 Obeo.
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *     Obeo - initial API and implementation
 *******************************************************************************/
export const LOADING__STATE = 'LOADING__STATE';
export const PROJECT_NOT_FOUND__STATE = 'PROJECT_NOT_FOUND__STATE';
export const PROJECT_FETCHING_ERROR__STATE = 'PROJECT_FETCHING_ERROR__STATE';
export const PROJECT_LOADED__STATE = 'PROJECT_LOADED__STATE';
export const PROJECT_AND_REPRESENTATION_LOADING__STATE = 'PROJECT_AND_REPRESENTATION_LOADING__STATE';
export const PROJECT_LOADED_AND_REPRESENTATION_DISPLAYED__STATE = 'PROJECT_LOADED_AND_REPRESENTATION_DISPLAYED__STATE';

export const HANDLE_FETCHED_PROJECT__ACTION = 'HANDLE_FETCHED_PROJECT__ACTION';
export const HANDLE_SELECTION__ACTION = 'HANDLE_SELECTION__ACTION';
export const HANDLE_REPRESENTATION_RENAMED__ACTION = 'HANDLE_REPRESENTATION_RENAMED__ACTION';
export const HANDLE_REPRESENTATION_LOADED__ACTION = 'HANDLE_REPRESENTATION_LOADED__ACTION';
export const HANDLE_SUBSCRIBERS_UPDATED__ACTION = 'HANDLE_SUBSCRIBERS_UPDATED__ACTION';

export const machine = {
  LOADING__STATE: {
    HANDLE_FETCHED_PROJECT__ACTION: [PROJECT_NOT_FOUND__STATE, PROJECT_FETCHING_ERROR__STATE, PROJECT_LOADED__STATE],
  },
  PROJECT_NOT_FOUND__STATE: {},
  PROJECT_FETCHING_ERROR__STATE: {},
  PROJECT_LOADED__STATE: {
    HANDLE_SELECTION__ACTION: [PROJECT_LOADED__STATE, PROJECT_LOADED_AND_REPRESENTATION_DISPLAYED__STATE],
    HANDLE_REPRESENTATION_RENAMED__ACTION: [PROJECT_LOADED__STATE, PROJECT_LOADED_AND_REPRESENTATION_DISPLAYED__STATE],
  },
  PROJECT_AND_REPRESENTATION_LOADING__STATE: {
    HANDLE_FETCHED_PROJECT__ACTION: [
      PROJECT_NOT_FOUND__STATE,
      PROJECT_FETCHING_ERROR__STATE,
      PROJECT_AND_REPRESENTATION_LOADING__STATE,
    ],
    HANDLE_REPRESENTATION_LOADED__ACTION: [PROJECT_LOADED_AND_REPRESENTATION_DISPLAYED__STATE],
  },
  PROJECT_LOADED_AND_REPRESENTATION_DISPLAYED__STATE: {
    HANDLE_SELECTION__ACTION: [PROJECT_LOADED__STATE, PROJECT_LOADED_AND_REPRESENTATION_DISPLAYED__STATE],
    HANDLE_REPRESENTATION_RENAMED__ACTION: [PROJECT_LOADED__STATE, PROJECT_LOADED_AND_REPRESENTATION_DISPLAYED__STATE],
    HANDLE_SUBSCRIBERS_UPDATED__ACTION: [PROJECT_LOADED_AND_REPRESENTATION_DISPLAYED__STATE],
  },
};
