/*******************************************************************************
 * Copyright (c) 2026 Obeo.
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *     Obeo - initial API and implementation
 *******************************************************************************/
package org.eclipse.sirius.components.view.diagram.provider.spec;

import java.util.Collection;

import org.eclipse.emf.common.notify.AdapterFactory;
import org.eclipse.sirius.components.view.ViewFactory;
import org.eclipse.sirius.components.view.diagram.DiagramFactory;
import org.eclipse.sirius.components.view.diagram.DiagramPackage;
import org.eclipse.sirius.components.view.diagram.EdgeDescription;
import org.eclipse.sirius.components.view.diagram.EdgeStyle;
import org.eclipse.sirius.components.view.diagram.NodeDescription;
import org.eclipse.sirius.components.view.diagram.provider.DefaultToolsFactory;
import org.eclipse.sirius.components.view.diagram.provider.DiagramDescriptionItemProvider;

/** Customization of the item provider implementation generated by EMF. */ public class DiagramDescriptionItemProviderSpec extends DiagramDescriptionItemProvider {     public DiagramDescriptionItemProviderSpec(AdapterFactory adapterFactory) {         super(adapterFactory);     }
    @Override
    public Object getImage(Object object) {
        return this.overlayImage(object, this.getResourceLocator().getImage("full/obj16/DiagramDescription.svg"));
    }

    @Override
    protected void collectNewChildDescriptors(Collection<Object> newChildDescriptors, Object object) {
        super.collectNewChildDescriptors(newChildDescriptors, object);
        DefaultToolsFactory defaultToolsFactory = new DefaultToolsFactory();

        newChildDescriptors.add(this.createChildParameter(DiagramPackage.Literals.DIAGRAM_DESCRIPTION__TOOLBAR, DiagramFactory.eINSTANCE.createDiagramToolbar()));
        newChildDescriptors.add(this.createChildParameter(DiagramPackage.Literals.DIAGRAM_DESCRIPTION__STYLE, DiagramFactory.eINSTANCE.createDiagramStyleDescription()));
        newChildDescriptors.add(this.createChildParameter(DiagramPackage.Literals.DIAGRAM_DESCRIPTION__CONDITIONAL_STYLES, DiagramFactory.eINSTANCE.createConditionalDiagramStyle()));
        newChildDescriptors.add(this.createChildParameter(DiagramPackage.Literals.DIAGRAM_DESCRIPTION__PALETTE, defaultToolsFactory.createDefaultDiagramPalette()));
        newChildDescriptors.add(this.createChildParameter(DiagramPackage.Literals.DIAGRAM_DESCRIPTION__GROUP_PALETTE, DiagramFactory.eINSTANCE.createGroupPalette()));
        newChildDescriptors.add(this.createChildParameter(DiagramPackage.Literals.DIAGRAM_DESCRIPTION__DECORATOR_DESCRIPTIONS, DiagramFactory.eINSTANCE.createNodeDecoratorDescription()));
        newChildDescriptors.add(this.createChildParameter(DiagramPackage.Literals.DIAGRAM_DESCRIPTION__DECORATOR_DESCRIPTIONS, DiagramFactory.eINSTANCE.createSemanticDecoratorDescription()));

        NodeDescription nodeChild = DiagramFactory.eINSTANCE.createNodeDescription();
        nodeChild.setName("Node");
        var style = DiagramFactory.eINSTANCE.createRectangularNodeStyleDescription();
        style.setChildrenLayoutStrategy(DiagramFactory.eINSTANCE.createFreeFormLayoutStrategyDescription());
        nodeChild.setStyle(style);
        nodeChild.setPalette(defaultToolsFactory.createDefaultNodePalette());
        nodeChild.setInsideLabel(defaultToolsFactory.createDefaultInsideLabelDescription());

        var defaultAction = DiagramFactory.eINSTANCE.createAction();
        defaultAction.setName("HideAction");
        defaultAction.setTooltipExpression("Hide");
        defaultAction.setIconURLsExpression("aql:'/icons/full/obj16/HideTool.svg'");
        var defaultActionService = ViewFactory.eINSTANCE.createChangeContext();
        defaultActionService.setExpression("aql:diagramServices.hide(Sequence{selectedNode})");
        defaultAction.getBody().add(defaultActionService);
        nodeChild.getActions().add(defaultAction);

        newChildDescriptors.add(this.createChildParameter(DiagramPackage.Literals.DIAGRAM_DESCRIPTION__NODE_DESCRIPTIONS, nodeChild));

        EdgeDescription edgeChild = DiagramFactory.eINSTANCE.createEdgeDescription();
        edgeChild.setName("Edge");
        EdgeStyle newEdgeStyle = DiagramFactory.eINSTANCE.createEdgeStyle();
        edgeChild.setStyle(newEdgeStyle);
        edgeChild.setPalette(defaultToolsFactory.createDefaultEdgePalette());
        newChildDescriptors.add(this.createChildParameter(DiagramPackage.Literals.DIAGRAM_DESCRIPTION__EDGE_DESCRIPTIONS, edgeChild));
    }

}
