/*******************************************************************************
 * Copyright (c) 2026 Obeo.
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *     Obeo - initial API and implementation
 *******************************************************************************/
package org.eclipse.sirius.components.view.diagram.provider.spec;

import java.util.Collection;

import org.eclipse.emf.common.notify.AdapterFactory;
import org.eclipse.sirius.components.view.diagram.DiagramFactory;
import org.eclipse.sirius.components.view.diagram.DiagramPackage;
import org.eclipse.sirius.components.view.diagram.provider.NodePaletteItemProvider;
import org.eclipse.sirius.components.view.diagram.provider.StudioDefaultToolsFactory;

/**
 * Customization of the item provider implementation generated by EMF.
 *
 * @author lfasani
 */
public class NodePaletteItemProviderSpec extends NodePaletteItemProvider {
    public NodePaletteItemProviderSpec(AdapterFactory adapterFactory) {
        super(adapterFactory);
    }

    @Override
    public Object getImage(Object object) {
        return this.overlayImage(object, this.getResourceLocator().getImage("full/obj16/NodePalette.svg"));
    }

    @Override
    protected void collectNewChildDescriptors(Collection<Object> newChildDescriptors, Object object) {
        StudioDefaultToolsFactory studioDefaultToolsFactory = new StudioDefaultToolsFactory();
        newChildDescriptors.add(this.createChildParameter(DiagramPackage.Literals.NODE_PALETTE__DELETE_TOOL, studioDefaultToolsFactory.createDefaultDeleteTool()));
        newChildDescriptors.add(this.createChildParameter(DiagramPackage.Literals.NODE_PALETTE__LABEL_EDIT_TOOL, studioDefaultToolsFactory.createDefaultLabelEditTool()));
        newChildDescriptors.add(this.createChildParameter(DiagramPackage.Literals.NODE_PALETTE__DROP_NODE_TOOL, DiagramFactory.eINSTANCE.createDropNodeTool()));
        newChildDescriptors.add(this.createChildParameter(DiagramPackage.Literals.NODE_PALETTE__NODE_TOOLS, studioDefaultToolsFactory.createDefaultNodeCreationTool()));
        newChildDescriptors.add(this.createChildParameter(DiagramPackage.Literals.NODE_PALETTE__QUICK_ACCESS_TOOLS, studioDefaultToolsFactory.createDefaultNodeCreationTool()));
        newChildDescriptors.add(this.createChildParameter(DiagramPackage.Literals.NODE_PALETTE__EDGE_TOOLS, studioDefaultToolsFactory.createDefaultEdgeTool()));
        newChildDescriptors.add(this.createChildParameter(DiagramPackage.Literals.NODE_PALETTE__TOOL_SECTIONS, DiagramFactory.eINSTANCE.createNodeToolSection()));

    }

}
