/*******************************************************************************
 * Copyright (c) 2026 Obeo.
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *     Obeo - initial API and implementation
 *******************************************************************************/
package org.eclipse.sirius.components.view.diagram.provider.spec;

import java.util.Collection;

import org.eclipse.emf.common.notify.AdapterFactory;
import org.eclipse.sirius.components.view.ViewFactory;
import org.eclipse.sirius.components.view.diagram.DiagramFactory;
import org.eclipse.sirius.components.view.diagram.DiagramPackage;
import org.eclipse.sirius.components.view.diagram.FreeFormLayoutStrategyDescription;
import org.eclipse.sirius.components.view.diagram.IconLabelNodeStyleDescription;
import org.eclipse.sirius.components.view.diagram.ImageNodeStyleDescription;
import org.eclipse.sirius.components.view.diagram.ListLayoutStrategyDescription;
import org.eclipse.sirius.components.view.diagram.NodeDescription;
import org.eclipse.sirius.components.view.diagram.RectangularNodeStyleDescription;
import org.eclipse.sirius.components.view.diagram.provider.DefaultToolsFactory;
import org.eclipse.sirius.components.view.diagram.provider.NodeDescriptionItemProvider;

/** Customization of the item provider implementation generated by EMF. */ public class NodeDescriptionItemProviderSpec extends NodeDescriptionItemProvider {     public NodeDescriptionItemProviderSpec(AdapterFactory adapterFactory) {         super(adapterFactory);     }
    @Override
    public Object getImage(Object object) {
        return this.overlayImage(object, this.getResourceLocator().getImage("full/obj16/NodeDescription.svg"));
    }

    @Override
    protected void collectNewChildDescriptors(Collection<Object> newChildDescriptors, Object object) {
        super.collectNewChildDescriptors(newChildDescriptors, object);

        DefaultToolsFactory defaultToolsFactory = new DefaultToolsFactory();

        newChildDescriptors.add(this.createChildParameter(DiagramPackage.Literals.NODE_DESCRIPTION__PALETTE, defaultToolsFactory.createDefaultNodePalette()));
        newChildDescriptors.add(this.createChildParameter(DiagramPackage.Literals.NODE_DESCRIPTION__ACTIONS, DiagramFactory.eINSTANCE.createAction()));

        NodeDescription nodeChild = DiagramFactory.eINSTANCE.createNodeDescription();
        nodeChild.setName("Sub-node");
        var subNodeStyle = DiagramFactory.eINSTANCE.createRectangularNodeStyleDescription();
        subNodeStyle.setChildrenLayoutStrategy(DiagramFactory.eINSTANCE.createFreeFormLayoutStrategyDescription());
        nodeChild.setStyle(subNodeStyle);
        nodeChild.setPalette(defaultToolsFactory.createDefaultNodePalette());
        nodeChild.setInsideLabel(defaultToolsFactory.createDefaultInsideLabelDescription());

        var defaultAction = DiagramFactory.eINSTANCE.createAction();
        defaultAction.setName("HideAction");
        defaultAction.setTooltipExpression("Hide");
        defaultAction.setIconURLsExpression("aql:'/icons/full/obj16/HideTool.svg'");
        var defaultActionService = ViewFactory.eINSTANCE.createChangeContext();
        defaultActionService.setExpression("aql:diagramServices.hide(Sequence{selectedNode})");
        defaultAction.getBody().add(defaultActionService);
        nodeChild.getActions().add(defaultAction);

        newChildDescriptors.add(this.createChildParameter(DiagramPackage.Literals.NODE_DESCRIPTION__CHILDREN_DESCRIPTIONS, nodeChild));

        NodeDescription borderNodeChild = DiagramFactory.eINSTANCE.createNodeDescription();
        borderNodeChild.setName("Border node");
        var borderNodeStyle = DiagramFactory.eINSTANCE.createRectangularNodeStyleDescription();
        borderNodeStyle.setChildrenLayoutStrategy(DiagramFactory.eINSTANCE.createFreeFormLayoutStrategyDescription());
        borderNodeChild.setStyle(borderNodeStyle);
        borderNodeChild.setPalette(defaultToolsFactory.createDefaultNodePalette());
        borderNodeChild.getOutsideLabels().add(defaultToolsFactory.createDefaultOutsideLabelDescription());
        newChildDescriptors.add(this.createChildParameter(DiagramPackage.Literals.NODE_DESCRIPTION__BORDER_NODES_DESCRIPTIONS, borderNodeChild));

        newChildDescriptors.add(this.createChildParameter(DiagramPackage.Literals.NODE_DESCRIPTION__STYLE, DiagramFactory.eINSTANCE.createRectangularNodeStyleDescription()));
        newChildDescriptors.add(this.createChildParameter(DiagramPackage.Literals.NODE_DESCRIPTION__STYLE, DiagramFactory.eINSTANCE.createImageNodeStyleDescription()));
        newChildDescriptors.add(this.createChildParameter(DiagramPackage.Literals.NODE_DESCRIPTION__STYLE, DiagramFactory.eINSTANCE.createIconLabelNodeStyleDescription()));

        newChildDescriptors.add(this.createChildParameter(DiagramPackage.Literals.NODE_DESCRIPTION__CONDITIONAL_STYLES, DiagramFactory.eINSTANCE.createConditionalNodeStyle()));

        newChildDescriptors.add(this.createChildParameter(DiagramPackage.Literals.NODE_DESCRIPTION__INSIDE_LABEL, defaultToolsFactory.createDefaultInsideLabelDescription()));
        newChildDescriptors.add(this.createChildParameter(DiagramPackage.Literals.NODE_DESCRIPTION__OUTSIDE_LABELS, defaultToolsFactory.createDefaultOutsideLabelDescription()));
    }

    @Override
    public String getCreateChildText(Object owner, Object feature, Object child, Collection<?> selection) {
        String text = "";
        if (feature == DiagramPackage.Literals.NODE_DESCRIPTION__CHILDREN_DESCRIPTIONS) {
            text = "Sub-node";
        } else if (feature == DiagramPackage.Literals.NODE_DESCRIPTION__BORDER_NODES_DESCRIPTIONS) {
            text = "Border node";
        } else if (child instanceof RectangularNodeStyleDescription) {
            text = "Style Rectangular";
        } else if (child instanceof ImageNodeStyleDescription) {
            text = "Style Image";
        } else if (child instanceof IconLabelNodeStyleDescription) {
            text = "Style Icon-Label";
        } else if (child instanceof FreeFormLayoutStrategyDescription) {
            text = "Layout Free Form";
        } else if (child instanceof ListLayoutStrategyDescription) {
            text = "Layout List";
        } else {
            text = super.getCreateChildText(owner, feature, child, selection);
        }

        return text;
    }

}
