/*******************************************************************************
 * Copyright (c) 2026 Obeo.
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *     Obeo - initial API and implementation
 *******************************************************************************/
package org.eclipse.sirius.components.domain.provider.spec;

import org.eclipse.emf.common.notify.AdapterFactory;
import org.eclipse.sirius.components.domain.Attribute;
import org.eclipse.sirius.components.domain.provider.AttributeItemProvider;

/**
 * Customization of the item provider implementation generated by EMF.
 *
 * @author lfasani
 */
public class AttributeItemProviderSpec extends AttributeItemProvider {
    public AttributeItemProviderSpec(AdapterFactory adapterFactory) {
        super(adapterFactory);
    }

    @Override
    public Object getImage(Object object) {
        if (object instanceof Attribute attr) {
            String imageName = null;
            switch (attr.getType()) {
            case BOOLEAN:
                imageName = "Boolean";
                break;
            case STRING:
                imageName = "String";
                break;
            case NUMBER:
                imageName = "Number";
                break;
            default:
                imageName = "Invalid";
                break;
            }
            if (attr.isMany()) {
                imageName = "Many" + imageName;
            }
            return this.overlayImage(object, this.getResourceLocator().getImage("full/obj16/" + imageName + "Attribute.svg"));
        }
        return this.overlayImage(object, this.getResourceLocator().getImage("full/obj16/Attribute"));
    }
}
