/*******************************************************************************
 * Copyright (c) 2026 Obeo.
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *     Obeo - initial API and implementation
 *******************************************************************************/
package org.eclipse.sirius.components.domain.provider.spec;

import java.util.Collection;
import java.util.List;

import org.eclipse.emf.common.notify.AdapterFactory;
import org.eclipse.emf.edit.provider.ComposedImage;
import org.eclipse.sirius.components.domain.Attribute;
import org.eclipse.sirius.components.domain.DataType;
import org.eclipse.sirius.components.domain.DomainFactory;
import org.eclipse.sirius.components.domain.DomainPackage;
import org.eclipse.sirius.components.domain.Entity;
import org.eclipse.sirius.components.domain.Relation;
import org.eclipse.sirius.components.domain.provider.EntityItemProvider;

/**
 * Customization of the item provider implementation generated by EMF.
 *
 * @author lfasani
 */
public class EntityItemProviderSpec extends EntityItemProvider {
    public EntityItemProviderSpec(AdapterFactory adapterFactory) {
        super(adapterFactory);
    }

    @Override
    public Object getImage(Object object) {
        Entity entity = (Entity) object;
        if (entity.isAbstract()) {
            return new ComposedImage(List.of(this.overlayImage(object, this.getResourceLocator().getImage("full/obj16/Entity.svg")), this.getResourceLocator()
                    .getImage("full/obj16/Abstract.svg")));
        }
        return this.overlayImage(object, this.getResourceLocator().getImage("full/obj16/Entity.svg"));
    }

    @Override
    protected void collectNewChildDescriptors(Collection<Object> newChildDescriptors, Object object) {
        Attribute newAttribute = DomainFactory.eINSTANCE.createAttribute();
        newAttribute.setName("newString");
        newAttribute.setType(DataType.STRING);
        newChildDescriptors.add(this.createChildParameter(DomainPackage.Literals.ENTITY__ATTRIBUTES, newAttribute));

        Relation newRelation = DomainFactory.eINSTANCE.createRelation();
        newRelation.setName("relation");
        newRelation.setMany(true);
        if (object instanceof Entity owner) {
            newRelation.setTargetType(owner);
        }
        newChildDescriptors.add(this.createChildParameter(DomainPackage.Literals.ENTITY__RELATIONS, newRelation));
    }
}
