= Create View

NOTE: This operation is specific to xref:user-manual:reference-documentation/studio-runtime/view-model/representation-diagram/index.adoc[Diagram Representations].

A `Create View` operation creates a new diagram element in a diagram representation. The created diagram element is assigned to a variable.

This is useful for modifying a diagram as a result of a user interaction.

== Examples

.Creating a new node in a diagram
====
This assumes the View Model contains a `Node Description` "Node_Entity" that represents a `Domain::Entity` as a `Node` in the contextual `Diagram Description`.

.Variables before
------
"self" : someDiagram(nodes: Sequence{})
"entity" : entity1
------

.Operation
------
CreateView(parentExpression: "var:someDiagram",
            elementDescription: Node_Entity
            semanticElementExpression: "var: entity"
            variableName: entityAsNode
            containmentKind: Diagram::NodeContainmentKind.CHILD_NODE)
------

.Variables after
------
"self" : someDiagram(nodes: Sequence{node1})
"entity" : entity1
"entityAsNode" : node1
------
====

== Properties

.Properties of `Create View` operation
[cols="1,1,3"]
|===
|_Property_
|_Type_
|_Semantics_

|*`Parent Expression`*
|`String` (expression)
|An expression that returns the graphical element of the diagram that will contain the newly-created graphical element.

|*`Element Description`*
|`Diagram::DiagramElementDescription`
|The `DiagramElementDescription` to instantiate.

|*`Semantic Element Expression`*
|`String` (expression)
|An expression that returns the semantic target of the created diagram element.

|*`Variable Name`*
|`String`
|The name of the variable to which the created diagram element is assigned.

|*`Containment Kind`*
|`Diagram::NodeContainmentKind`
a|The strategy regarding how the created diagram element integrates into the diagram:

* CHILD_NODE: if the created diagram element is a node, places the node as a _child node_ of the parent node.
* BORDER_NODE: if the created diagram element is a node, places the node as a _border node_ of the parent node.
|===