= Model Operations

A _Model Operation_ is used to specify an arbitrary behavior in an imperative manner.

[IMPORTANT] 
.Operation Execution Context
==== 
Each operation is executed in a context made of _variables_.
A _variable_ is essentially a _name_ attached to a _value_.
Some operations may impact the context, usually by defining new variables or modifying the value attached to a variable.

The context in which an operation is executed is _most of the time_ provided by the parent operation.
That is, a child model operation is executed in the context resulting from the execution of the parent model operation.

Root model operations are executed in a context provided by the parent element.
Depending on the nature of that element, the available variables and the values to which they are bound will vary.
To understand the context of a model operation, refer to the documentation of the parent element.
====

== Control Flow Operations

include::user-manual:reference-documentation/studio-definition/view-model/commons-action/model-operations/change-context.adoc[leveloffset=+1]

include::user-manual:reference-documentation/studio-definition/view-model/commons-action/model-operations/let.adoc[leveloffset=+1]

include::user-manual:reference-documentation/studio-definition/view-model/commons-action/model-operations/if.adoc[leveloffset=+1]

== Model Change Operations

When executed, the operations below have side-effects on the semantic model.

include::user-manual:reference-documentation/studio-definition/view-model/commons-action/model-operations/create-instance.adoc[leveloffset=+1]

include::user-manual:reference-documentation/studio-definition/view-model/commons-action/model-operations/set-value.adoc[leveloffset=+1]

include::user-manual:reference-documentation/studio-definition/view-model/commons-action/model-operations/unset-value.adoc[leveloffset=+1]

include::user-manual:reference-documentation/studio-definition/view-model/commons-action/model-operations/delete-element.adoc[leveloffset=+1]

== Representation Operations

When executed, the operations below have side-effects on the representations of the model.

include::user-manual:reference-documentation/studio-definition/view-model/commons-action/model-operations/create-view.adoc[leveloffset=+1]

include::user-manual:reference-documentation/studio-definition/view-model/commons-action/model-operations/delete-view.adoc[leveloffset=+1]