= Card

== Usage

Cards are used to display a set of properties of an element.
A card can contain various subcomponents with various layouts and actions.
If you want to display a large set of cards with a small amount of information, a list may be more relevant.

== Behavior

Cards may be available in various width.
Once on screen, a card will have a constant width but its height may change.
Cards could be collapsed to reduce the amount of information displayed.
A collection of card may be filterable and/or sortable.

== Content

Cards provide a bird eye view of complex information.
Do not try to fill cards with more information than necessary.


== Actions

The card itself can be an action.
As such, it can act as a link to another page.
Actions can be added to the card thanks to icons, text or buttons.
Do not add more than two button-based actions to the card.

== Specification

Cards can be created by mixin various content blocks including:

* Hero Title
* Primary Title
* Secondary Title
* Text
* Actions
* List components
* TabBar component

Those components can be combined in various ways.