services:
  database:
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --username=username --dbname=postgres"]
      interval: 2s
      timeout: 3s
      retries: 10

  backend:
    pull_policy: never
    depends_on:
      database:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_PROFILES_ACTIVE: e2e
      SIRIUS_COMPONENTS_DIAGRAM_DEBUG: true
      SIRIUS_WEB_TREE_NEW-PALETTE_ENABLED: true
      MANAGEMENT_HEALTH_ELASTICSEARCH_ENABLED: false
