################################################################################
# Copyright (c) 2025, 2026 Obeo.
# This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#     Obeo - initial API and implementation
#################################################################################
TABLE_CELL_EDIT_ERROR=Something went wrong while handling the cell edit operations
UNSUPPORTED_TABLE_CELL_WIDGET_ERROR=Not supported cell widget
INVOKE_ACTION_ERROR=Something went wrong while executing the action "{0}".
CORE_PROPERTIES=Core Properties
ADJUST_SIZE=Adjust size
RESET_OUTSIDE_LABEL_POSITION=Reset outside labels positions
RESET_LABEL_SIZE=Reset labels sizes
RESET_HANDLES_POSITION=Reset handles positions
RESET_BENDING_POINTS=Reset bending points
COLLAPSE=Collapse
EXPAND=Expand
DELETE_FROM_MODEl=Delete from model
FADE=Fade
UNFADE=Unfade
HIDE=Hide
PIN=Pin
UNPIN=Unpin
EDIT=Edit
DEFAULT_SELECTION_DIALOG_TITLE=Element Selection
DEFAULT_SELECTION_DIALOG_WITH_OPTIONAL_SELECTION_DESCRIPTION=A tool will be executed, choose how to proceed:
DEFAULT_SELECTION_DIALOG_WITH_MANDATORY_SELECTION_DESCRIPTION=A tool will be executed, select an element to proceed:
DEFAULT_SELECTION_DIALOG_NO_SELECTION_ACTION_LABEL=Execute the tool without making a selection
DEFAULT_SELECTION_DIALOG_NO_SELECTION_ACTION_DESCRIPTION=Proceed without selecting an existing element
DEFAULT_SELECTION_DIALOG_WITH_SELECTION_ACTION_LABEL=Use an existing element
DEFAULT_SELECTION_DIALOG_WITH_SELECTION_ACTION_DESCRIPTION=Select one or more elements
DEFAULT_SELECTION_DIALOG_NO_SELECTION_ACTION_STATUS_MESSAGE=The tool execution will continue without any element selected
DEFAULT_SELECTION_DIALOG_SELECTION_REQUIRED_WITHOUT_SELECTION_STATUS_MESSAGE=Select at least one element to continue the tool execution
DEFAULT_SELECTION_DIALOG_SELECTION_REQUIRED_WITH_ONE_SELECTED_ELEMENT_STATUS_MESSAGE=The tool execution will continue with {0}
DEFAULT_SELECTION_DIALOG_SELECTION_REQUIRED_WITH_MANY_SELECTED_ELEMENTS_STATUS_MESSAGE=The tool execution will continue with {0} elements
DEFAULT_SELECTION_DIALOG_CONFIRM_BUTTON_LABEL=Confirm
DEFAULT_SELECTION_DIALOG_SELECTION_REQUIRED_WITHOUT_SELECTION_CONFIRM_BUTTON_LABEL=Select an element
