/*******************************************************************************
 * Copyright (c) 2021, 2026 Obeo.
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *     Obeo - initial API and implementation
 *******************************************************************************/
package org.eclipse.sirius.components.view.form.provider;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;
import org.eclipse.emf.common.util.ResourceLocator;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.edit.command.CommandParameter;
import org.eclipse.emf.edit.domain.EditingDomain;
import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ChildCreationExtenderManager;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IChildCreationExtender;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;
import org.eclipse.sirius.components.view.View;
import org.eclipse.sirius.components.view.ViewPackage;
import org.eclipse.sirius.components.view.form.FormDescription;
import org.eclipse.sirius.components.view.form.FormFactory;
import org.eclipse.sirius.components.view.form.FormPackage;
import org.eclipse.sirius.components.view.form.GroupDescription;
import org.eclipse.sirius.components.view.form.PageDescription;
import org.eclipse.sirius.components.view.form.util.FormAdapterFactory;
import org.eclipse.sirius.components.view.util.ViewSwitch;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers. The adapters generated by this
 * factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}. The adapters
 * also support Eclipse property sheets. Note that most of the adapters are shared among multiple instances. <!--
 * begin-user-doc --> <!-- end-user-doc -->
 *
 * @generated
 */
public class FormItemProviderAdapterFactory extends FormAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable, IChildCreationExtender {
    /**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc --> <!--
     * end-user-doc -->
	 * @generated
	 */
    protected ComposedAdapterFactory parentAdapterFactory;

    /**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc --> <!--
     * end-user-doc -->
	 * @generated
	 */
    protected IChangeNotifier changeNotifier = new ChangeNotifier();

    /**
	 * This helps manage the child creation extenders.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
    protected ChildCreationExtenderManager childCreationExtenderManager = new ChildCreationExtenderManager(FormEditPlugin.INSTANCE, FormPackage.eNS_URI);

    /**
     * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    protected Collection<Object> supportedTypes = new ArrayList<Object>();

    /**
	 * This constructs an instance.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
    public FormItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

    /**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sirius.components.view.form.FormDescription} instances.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
    protected FormDescriptionItemProvider formDescriptionItemProvider;

    /**
     * This creates an adapter for a {@link org.eclipse.sirius.components.view.form.FormDescription}. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter createFormDescriptionAdapter() {
		if (formDescriptionItemProvider == null)
		{
			formDescriptionItemProvider = new FormDescriptionItemProvider(this);
		}

		return formDescriptionItemProvider;
	}

    /**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sirius.components.view.form.FormVariable} instances.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
    protected FormVariableItemProvider formVariableItemProvider;

    /**
	 * This creates an adapter for a {@link org.eclipse.sirius.components.view.form.FormVariable}.
	 * <!-- begin-user-doc
     * --> <!-- end-user-doc -->
	 * @generated
	 */
    @Override
    public Adapter createFormVariableAdapter() {
		if (formVariableItemProvider == null)
		{
			formVariableItemProvider = new FormVariableItemProvider(this);
		}

		return formVariableItemProvider;
	}

    /**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sirius.components.view.form.PageDescription} instances.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
    protected PageDescriptionItemProvider pageDescriptionItemProvider;

    /**
     * This creates an adapter for a {@link org.eclipse.sirius.components.view.form.PageDescription}. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter createPageDescriptionAdapter() {
		if (pageDescriptionItemProvider == null)
		{
			pageDescriptionItemProvider = new PageDescriptionItemProvider(this);
		}

		return pageDescriptionItemProvider;
	}

    /**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sirius.components.view.form.GroupDescription} instances.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
    protected GroupDescriptionItemProvider groupDescriptionItemProvider;

    /**
     * This creates an adapter for a {@link org.eclipse.sirius.components.view.form.GroupDescription}. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter createGroupDescriptionAdapter() {
		if (groupDescriptionItemProvider == null)
		{
			groupDescriptionItemProvider = new GroupDescriptionItemProvider(this);
		}

		return groupDescriptionItemProvider;
	}

    /**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sirius.components.view.form.BarChartDescription} instances.
	 * <!-- begin-user-doc --> <!--
     * end-user-doc -->
	 * @generated
	 */
    protected BarChartDescriptionItemProvider barChartDescriptionItemProvider;

    /**
     * This creates an adapter for a {@link org.eclipse.sirius.components.view.form.BarChartDescription}. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter createBarChartDescriptionAdapter() {
		if (barChartDescriptionItemProvider == null)
		{
			barChartDescriptionItemProvider = new BarChartDescriptionItemProvider(this);
		}

		return barChartDescriptionItemProvider;
	}

    /**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sirius.components.view.form.SplitButtonDescription} instances.
	 * <!-- begin-user-doc --> <!--
     * end-user-doc -->
	 * @generated
	 */
    protected SplitButtonDescriptionItemProvider splitButtonDescriptionItemProvider;

    /**
     * This creates an adapter for a {@link org.eclipse.sirius.components.view.form.SplitButtonDescription}. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter createSplitButtonDescriptionAdapter() {
		if (splitButtonDescriptionItemProvider == null)
		{
			splitButtonDescriptionItemProvider = new SplitButtonDescriptionItemProvider(this);
		}

		return splitButtonDescriptionItemProvider;
	}

    /**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sirius.components.view.form.ButtonDescription} instances.
	 * <!-- begin-user-doc --> <!--
     * end-user-doc -->
	 * @generated
	 */
    protected ButtonDescriptionItemProvider buttonDescriptionItemProvider;

    /**
     * This creates an adapter for a {@link org.eclipse.sirius.components.view.form.ButtonDescription}. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter createButtonDescriptionAdapter() {
		if (buttonDescriptionItemProvider == null)
		{
			buttonDescriptionItemProvider = new ButtonDescriptionItemProvider(this);
		}

		return buttonDescriptionItemProvider;
	}

    /**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sirius.components.view.form.CheckboxDescription} instances.
	 * <!-- begin-user-doc --> <!--
     * end-user-doc -->
	 * @generated
	 */
    protected CheckboxDescriptionItemProvider checkboxDescriptionItemProvider;

    /**
     * This creates an adapter for a {@link org.eclipse.sirius.components.view.form.CheckboxDescription}. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter createCheckboxDescriptionAdapter() {
		if (checkboxDescriptionItemProvider == null)
		{
			checkboxDescriptionItemProvider = new CheckboxDescriptionItemProvider(this);
		}

		return checkboxDescriptionItemProvider;
	}

    /**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sirius.components.view.form.FlexboxContainerDescription} instances.
	 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
	 * @generated
	 */
    protected FlexboxContainerDescriptionItemProvider flexboxContainerDescriptionItemProvider;

    /**
     * This creates an adapter for a {@link org.eclipse.sirius.components.view.form.FlexboxContainerDescription}. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter createFlexboxContainerDescriptionAdapter() {
		if (flexboxContainerDescriptionItemProvider == null)
		{
			flexboxContainerDescriptionItemProvider = new FlexboxContainerDescriptionItemProvider(this);
		}

		return flexboxContainerDescriptionItemProvider;
	}

    /**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sirius.components.view.form.ImageDescription} instances.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
    protected ImageDescriptionItemProvider imageDescriptionItemProvider;

    /**
     * This creates an adapter for a {@link org.eclipse.sirius.components.view.form.ImageDescription}. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter createImageDescriptionAdapter() {
		if (imageDescriptionItemProvider == null)
		{
			imageDescriptionItemProvider = new ImageDescriptionItemProvider(this);
		}

		return imageDescriptionItemProvider;
	}

    /**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sirius.components.view.form.LabelDescription} instances.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
    protected LabelDescriptionItemProvider labelDescriptionItemProvider;

    /**
     * This creates an adapter for a {@link org.eclipse.sirius.components.view.form.LabelDescription}. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter createLabelDescriptionAdapter() {
		if (labelDescriptionItemProvider == null)
		{
			labelDescriptionItemProvider = new LabelDescriptionItemProvider(this);
		}

		return labelDescriptionItemProvider;
	}

    /**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sirius.components.view.form.LinkDescription} instances.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
    protected LinkDescriptionItemProvider linkDescriptionItemProvider;

    /**
     * This creates an adapter for a {@link org.eclipse.sirius.components.view.form.LinkDescription}. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter createLinkDescriptionAdapter() {
		if (linkDescriptionItemProvider == null)
		{
			linkDescriptionItemProvider = new LinkDescriptionItemProvider(this);
		}

		return linkDescriptionItemProvider;
	}

    /**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sirius.components.view.form.ListDescription} instances.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
    protected ListDescriptionItemProvider listDescriptionItemProvider;

    /**
     * This creates an adapter for a {@link org.eclipse.sirius.components.view.form.ListDescription}. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter createListDescriptionAdapter() {
		if (listDescriptionItemProvider == null)
		{
			listDescriptionItemProvider = new ListDescriptionItemProvider(this);
		}

		return listDescriptionItemProvider;
	}

    /**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sirius.components.view.form.MultiSelectDescription} instances.
	 * <!-- begin-user-doc --> <!--
     * end-user-doc -->
	 * @generated
	 */
    protected MultiSelectDescriptionItemProvider multiSelectDescriptionItemProvider;

    /**
     * This creates an adapter for a {@link org.eclipse.sirius.components.view.form.MultiSelectDescription}. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter createMultiSelectDescriptionAdapter() {
		if (multiSelectDescriptionItemProvider == null)
		{
			multiSelectDescriptionItemProvider = new MultiSelectDescriptionItemProvider(this);
		}

		return multiSelectDescriptionItemProvider;
	}

    /**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sirius.components.view.form.TreeDescription} instances.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
    protected TreeDescriptionItemProvider treeDescriptionItemProvider;

    /**
     * This creates an adapter for a {@link org.eclipse.sirius.components.view.form.TreeDescription}. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter createTreeDescriptionAdapter() {
		if (treeDescriptionItemProvider == null)
		{
			treeDescriptionItemProvider = new TreeDescriptionItemProvider(this);
		}

		return treeDescriptionItemProvider;
	}

    /**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sirius.components.view.form.DateTimeDescription} instances.
	 * <!-- begin-user-doc --> <!--
     * end-user-doc -->
	 * @generated
	 */
    protected DateTimeDescriptionItemProvider dateTimeDescriptionItemProvider;

    /**
     * This creates an adapter for a {@link org.eclipse.sirius.components.view.form.DateTimeDescription}. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter createDateTimeDescriptionAdapter() {
		if (dateTimeDescriptionItemProvider == null)
		{
			dateTimeDescriptionItemProvider = new DateTimeDescriptionItemProvider(this);
		}

		return dateTimeDescriptionItemProvider;
	}

    /**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sirius.components.view.form.SliderDescription} instances.
	 * <!-- begin-user-doc --> <!--
     * end-user-doc -->
	 * @generated
	 */
    protected SliderDescriptionItemProvider sliderDescriptionItemProvider;

    /**
     * This creates an adapter for a {@link org.eclipse.sirius.components.view.form.SliderDescription}. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter createSliderDescriptionAdapter() {
		if (sliderDescriptionItemProvider == null)
		{
			sliderDescriptionItemProvider = new SliderDescriptionItemProvider(this);
		}

		return sliderDescriptionItemProvider;
	}

    /**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sirius.components.view.form.PieChartDescription} instances.
	 * <!-- begin-user-doc --> <!--
     * end-user-doc -->
	 * @generated
	 */
    protected PieChartDescriptionItemProvider pieChartDescriptionItemProvider;

    /**
     * This creates an adapter for a {@link org.eclipse.sirius.components.view.form.PieChartDescription}. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter createPieChartDescriptionAdapter() {
		if (pieChartDescriptionItemProvider == null)
		{
			pieChartDescriptionItemProvider = new PieChartDescriptionItemProvider(this);
		}

		return pieChartDescriptionItemProvider;
	}

    /**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sirius.components.view.form.RadioDescription} instances.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
    protected RadioDescriptionItemProvider radioDescriptionItemProvider;

    /**
     * This creates an adapter for a {@link org.eclipse.sirius.components.view.form.RadioDescription}. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter createRadioDescriptionAdapter() {
		if (radioDescriptionItemProvider == null)
		{
			radioDescriptionItemProvider = new RadioDescriptionItemProvider(this);
		}

		return radioDescriptionItemProvider;
	}

    /**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sirius.components.view.form.RichTextDescription} instances.
	 * <!-- begin-user-doc --> <!--
     * end-user-doc -->
	 * @generated
	 */
    protected RichTextDescriptionItemProvider richTextDescriptionItemProvider;

    /**
     * This creates an adapter for a {@link org.eclipse.sirius.components.view.form.RichTextDescription}. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter createRichTextDescriptionAdapter() {
		if (richTextDescriptionItemProvider == null)
		{
			richTextDescriptionItemProvider = new RichTextDescriptionItemProvider(this);
		}

		return richTextDescriptionItemProvider;
	}

    /**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sirius.components.view.form.SelectDescription} instances.
	 * <!-- begin-user-doc --> <!--
     * end-user-doc -->
	 * @generated
	 */
    protected SelectDescriptionItemProvider selectDescriptionItemProvider;

    /**
     * This creates an adapter for a {@link org.eclipse.sirius.components.view.form.SelectDescription}. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter createSelectDescriptionAdapter() {
		if (selectDescriptionItemProvider == null)
		{
			selectDescriptionItemProvider = new SelectDescriptionItemProvider(this);
		}

		return selectDescriptionItemProvider;
	}

    /**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sirius.components.view.form.TextAreaDescription} instances.
	 * <!-- begin-user-doc --> <!--
     * end-user-doc -->
	 * @generated
	 */
    protected TextAreaDescriptionItemProvider textAreaDescriptionItemProvider;

    /**
     * This creates an adapter for a {@link org.eclipse.sirius.components.view.form.TextAreaDescription}. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter createTextAreaDescriptionAdapter() {
		if (textAreaDescriptionItemProvider == null)
		{
			textAreaDescriptionItemProvider = new TextAreaDescriptionItemProvider(this);
		}

		return textAreaDescriptionItemProvider;
	}

    /**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sirius.components.view.form.TextfieldDescription} instances.
	 * <!-- begin-user-doc --> <!--
     * end-user-doc -->
	 * @generated
	 */
    protected TextfieldDescriptionItemProvider textfieldDescriptionItemProvider;

    /**
     * This creates an adapter for a {@link org.eclipse.sirius.components.view.form.TextfieldDescription}. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter createTextfieldDescriptionAdapter() {
		if (textfieldDescriptionItemProvider == null)
		{
			textfieldDescriptionItemProvider = new TextfieldDescriptionItemProvider(this);
		}

		return textfieldDescriptionItemProvider;
	}

    /**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sirius.components.view.form.BarChartDescriptionStyle} instances.
	 * <!-- begin-user-doc --> <!--
     * end-user-doc -->
	 * @generated
	 */
    protected BarChartDescriptionStyleItemProvider barChartDescriptionStyleItemProvider;

    /**
     * This creates an adapter for a {@link org.eclipse.sirius.components.view.form.BarChartDescriptionStyle}. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter createBarChartDescriptionStyleAdapter() {
		if (barChartDescriptionStyleItemProvider == null)
		{
			barChartDescriptionStyleItemProvider = new BarChartDescriptionStyleItemProvider(this);
		}

		return barChartDescriptionStyleItemProvider;
	}

    /**
     * This keeps track of the one adapter used for all
     * {@link org.eclipse.sirius.components.view.form.ConditionalBarChartDescriptionStyle} instances. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    protected ConditionalBarChartDescriptionStyleItemProvider conditionalBarChartDescriptionStyleItemProvider;

    /**
	 * This creates an adapter for a {@link org.eclipse.sirius.components.view.form.ConditionalBarChartDescriptionStyle}.
	 * <!-- begin-user-doc --> <!--
     * end-user-doc -->
	 * @generated
	 */
    @Override
    public Adapter createConditionalBarChartDescriptionStyleAdapter() {
		if (conditionalBarChartDescriptionStyleItemProvider == null)
		{
			conditionalBarChartDescriptionStyleItemProvider = new ConditionalBarChartDescriptionStyleItemProvider(this);
		}

		return conditionalBarChartDescriptionStyleItemProvider;
	}

    /**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sirius.components.view.form.ButtonDescriptionStyle} instances.
	 * <!-- begin-user-doc --> <!--
     * end-user-doc -->
	 * @generated
	 */
    protected ButtonDescriptionStyleItemProvider buttonDescriptionStyleItemProvider;

    /**
     * This creates an adapter for a {@link org.eclipse.sirius.components.view.form.ButtonDescriptionStyle}. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter createButtonDescriptionStyleAdapter() {
		if (buttonDescriptionStyleItemProvider == null)
		{
			buttonDescriptionStyleItemProvider = new ButtonDescriptionStyleItemProvider(this);
		}

		return buttonDescriptionStyleItemProvider;
	}

    /**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sirius.components.view.form.ConditionalButtonDescriptionStyle} instances.
	 * <!-- begin-user-doc
     * --> <!-- end-user-doc -->
	 * @generated
	 */
    protected ConditionalButtonDescriptionStyleItemProvider conditionalButtonDescriptionStyleItemProvider;

    /**
	 * This creates an adapter for a {@link org.eclipse.sirius.components.view.form.ConditionalButtonDescriptionStyle}.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
    @Override
    public Adapter createConditionalButtonDescriptionStyleAdapter() {
		if (conditionalButtonDescriptionStyleItemProvider == null)
		{
			conditionalButtonDescriptionStyleItemProvider = new ConditionalButtonDescriptionStyleItemProvider(this);
		}

		return conditionalButtonDescriptionStyleItemProvider;
	}

    /**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sirius.components.view.form.CheckboxDescriptionStyle} instances.
	 * <!-- begin-user-doc --> <!--
     * end-user-doc -->
	 * @generated
	 */
    protected CheckboxDescriptionStyleItemProvider checkboxDescriptionStyleItemProvider;

    /**
     * This creates an adapter for a {@link org.eclipse.sirius.components.view.form.CheckboxDescriptionStyle}. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter createCheckboxDescriptionStyleAdapter() {
		if (checkboxDescriptionStyleItemProvider == null)
		{
			checkboxDescriptionStyleItemProvider = new CheckboxDescriptionStyleItemProvider(this);
		}

		return checkboxDescriptionStyleItemProvider;
	}

    /**
     * This keeps track of the one adapter used for all
     * {@link org.eclipse.sirius.components.view.form.ConditionalCheckboxDescriptionStyle} instances. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    protected ConditionalCheckboxDescriptionStyleItemProvider conditionalCheckboxDescriptionStyleItemProvider;

    /**
	 * This creates an adapter for a {@link org.eclipse.sirius.components.view.form.ConditionalCheckboxDescriptionStyle}.
	 * <!-- begin-user-doc --> <!--
     * end-user-doc -->
	 * @generated
	 */
    @Override
    public Adapter createConditionalCheckboxDescriptionStyleAdapter() {
		if (conditionalCheckboxDescriptionStyleItemProvider == null)
		{
			conditionalCheckboxDescriptionStyleItemProvider = new ConditionalCheckboxDescriptionStyleItemProvider(this);
		}

		return conditionalCheckboxDescriptionStyleItemProvider;
	}

    /**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sirius.components.view.form.LabelDescriptionStyle} instances.
	 * <!-- begin-user-doc --> <!--
     * end-user-doc -->
	 * @generated
	 */
    protected LabelDescriptionStyleItemProvider labelDescriptionStyleItemProvider;

    /**
     * This creates an adapter for a {@link org.eclipse.sirius.components.view.form.LabelDescriptionStyle}. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter createLabelDescriptionStyleAdapter() {
		if (labelDescriptionStyleItemProvider == null)
		{
			labelDescriptionStyleItemProvider = new LabelDescriptionStyleItemProvider(this);
		}

		return labelDescriptionStyleItemProvider;
	}

    /**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sirius.components.view.form.ConditionalLabelDescriptionStyle} instances.
	 * <!-- begin-user-doc
     * --> <!-- end-user-doc -->
	 * @generated
	 */
    protected ConditionalLabelDescriptionStyleItemProvider conditionalLabelDescriptionStyleItemProvider;

    /**
	 * This creates an adapter for a {@link org.eclipse.sirius.components.view.form.ConditionalLabelDescriptionStyle}.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
    @Override
    public Adapter createConditionalLabelDescriptionStyleAdapter() {
		if (conditionalLabelDescriptionStyleItemProvider == null)
		{
			conditionalLabelDescriptionStyleItemProvider = new ConditionalLabelDescriptionStyleItemProvider(this);
		}

		return conditionalLabelDescriptionStyleItemProvider;
	}

    /**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sirius.components.view.form.LinkDescriptionStyle} instances.
	 * <!-- begin-user-doc --> <!--
     * end-user-doc -->
	 * @generated
	 */
    protected LinkDescriptionStyleItemProvider linkDescriptionStyleItemProvider;

    /**
     * This creates an adapter for a {@link org.eclipse.sirius.components.view.form.LinkDescriptionStyle}. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter createLinkDescriptionStyleAdapter() {
		if (linkDescriptionStyleItemProvider == null)
		{
			linkDescriptionStyleItemProvider = new LinkDescriptionStyleItemProvider(this);
		}

		return linkDescriptionStyleItemProvider;
	}

    /**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sirius.components.view.form.ConditionalLinkDescriptionStyle} instances.
	 * <!-- begin-user-doc
     * --> <!-- end-user-doc -->
	 * @generated
	 */
    protected ConditionalLinkDescriptionStyleItemProvider conditionalLinkDescriptionStyleItemProvider;

    /**
	 * This creates an adapter for a {@link org.eclipse.sirius.components.view.form.ConditionalLinkDescriptionStyle}.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
    @Override
    public Adapter createConditionalLinkDescriptionStyleAdapter() {
		if (conditionalLinkDescriptionStyleItemProvider == null)
		{
			conditionalLinkDescriptionStyleItemProvider = new ConditionalLinkDescriptionStyleItemProvider(this);
		}

		return conditionalLinkDescriptionStyleItemProvider;
	}

    /**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sirius.components.view.form.ListDescriptionStyle} instances.
	 * <!-- begin-user-doc --> <!--
     * end-user-doc -->
	 * @generated
	 */
    protected ListDescriptionStyleItemProvider listDescriptionStyleItemProvider;

    /**
     * This creates an adapter for a {@link org.eclipse.sirius.components.view.form.ListDescriptionStyle}. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter createListDescriptionStyleAdapter() {
		if (listDescriptionStyleItemProvider == null)
		{
			listDescriptionStyleItemProvider = new ListDescriptionStyleItemProvider(this);
		}

		return listDescriptionStyleItemProvider;
	}

    /**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sirius.components.view.form.ConditionalListDescriptionStyle} instances.
	 * <!-- begin-user-doc
     * --> <!-- end-user-doc -->
	 * @generated
	 */
    protected ConditionalListDescriptionStyleItemProvider conditionalListDescriptionStyleItemProvider;

    /**
	 * This creates an adapter for a {@link org.eclipse.sirius.components.view.form.ConditionalListDescriptionStyle}.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
    @Override
    public Adapter createConditionalListDescriptionStyleAdapter() {
		if (conditionalListDescriptionStyleItemProvider == null)
		{
			conditionalListDescriptionStyleItemProvider = new ConditionalListDescriptionStyleItemProvider(this);
		}

		return conditionalListDescriptionStyleItemProvider;
	}

    /**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sirius.components.view.form.MultiSelectDescriptionStyle} instances.
	 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
	 * @generated
	 */
    protected MultiSelectDescriptionStyleItemProvider multiSelectDescriptionStyleItemProvider;

    /**
     * This creates an adapter for a {@link org.eclipse.sirius.components.view.form.MultiSelectDescriptionStyle}. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter createMultiSelectDescriptionStyleAdapter() {
		if (multiSelectDescriptionStyleItemProvider == null)
		{
			multiSelectDescriptionStyleItemProvider = new MultiSelectDescriptionStyleItemProvider(this);
		}

		return multiSelectDescriptionStyleItemProvider;
	}

    /**
     * This keeps track of the one adapter used for all
     * {@link org.eclipse.sirius.components.view.form.ConditionalMultiSelectDescriptionStyle} instances. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    protected ConditionalMultiSelectDescriptionStyleItemProvider conditionalMultiSelectDescriptionStyleItemProvider;

    /**
	 * This creates an adapter for a {@link org.eclipse.sirius.components.view.form.ConditionalMultiSelectDescriptionStyle}.
	 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
	 * @generated
	 */
    @Override
    public Adapter createConditionalMultiSelectDescriptionStyleAdapter() {
		if (conditionalMultiSelectDescriptionStyleItemProvider == null)
		{
			conditionalMultiSelectDescriptionStyleItemProvider = new ConditionalMultiSelectDescriptionStyleItemProvider(this);
		}

		return conditionalMultiSelectDescriptionStyleItemProvider;
	}

    /**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sirius.components.view.form.PieChartDescriptionStyle} instances.
	 * <!-- begin-user-doc --> <!--
     * end-user-doc -->
	 * @generated
	 */
    protected PieChartDescriptionStyleItemProvider pieChartDescriptionStyleItemProvider;

    /**
     * This creates an adapter for a {@link org.eclipse.sirius.components.view.form.PieChartDescriptionStyle}. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter createPieChartDescriptionStyleAdapter() {
		if (pieChartDescriptionStyleItemProvider == null)
		{
			pieChartDescriptionStyleItemProvider = new PieChartDescriptionStyleItemProvider(this);
		}

		return pieChartDescriptionStyleItemProvider;
	}

    /**
     * This keeps track of the one adapter used for all
     * {@link org.eclipse.sirius.components.view.form.ConditionalPieChartDescriptionStyle} instances. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    protected ConditionalPieChartDescriptionStyleItemProvider conditionalPieChartDescriptionStyleItemProvider;

    /**
	 * This creates an adapter for a {@link org.eclipse.sirius.components.view.form.ConditionalPieChartDescriptionStyle}.
	 * <!-- begin-user-doc --> <!--
     * end-user-doc -->
	 * @generated
	 */
    @Override
    public Adapter createConditionalPieChartDescriptionStyleAdapter() {
		if (conditionalPieChartDescriptionStyleItemProvider == null)
		{
			conditionalPieChartDescriptionStyleItemProvider = new ConditionalPieChartDescriptionStyleItemProvider(this);
		}

		return conditionalPieChartDescriptionStyleItemProvider;
	}

    /**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sirius.components.view.form.RadioDescriptionStyle} instances.
	 * <!-- begin-user-doc --> <!--
     * end-user-doc -->
	 * @generated
	 */
    protected RadioDescriptionStyleItemProvider radioDescriptionStyleItemProvider;

    /**
     * This creates an adapter for a {@link org.eclipse.sirius.components.view.form.RadioDescriptionStyle}. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter createRadioDescriptionStyleAdapter() {
		if (radioDescriptionStyleItemProvider == null)
		{
			radioDescriptionStyleItemProvider = new RadioDescriptionStyleItemProvider(this);
		}

		return radioDescriptionStyleItemProvider;
	}

    /**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sirius.components.view.form.ConditionalRadioDescriptionStyle} instances.
	 * <!-- begin-user-doc
     * --> <!-- end-user-doc -->
	 * @generated
	 */
    protected ConditionalRadioDescriptionStyleItemProvider conditionalRadioDescriptionStyleItemProvider;

    /**
	 * This creates an adapter for a {@link org.eclipse.sirius.components.view.form.ConditionalRadioDescriptionStyle}.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
    @Override
    public Adapter createConditionalRadioDescriptionStyleAdapter() {
		if (conditionalRadioDescriptionStyleItemProvider == null)
		{
			conditionalRadioDescriptionStyleItemProvider = new ConditionalRadioDescriptionStyleItemProvider(this);
		}

		return conditionalRadioDescriptionStyleItemProvider;
	}

    /**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sirius.components.view.form.SelectDescriptionStyle} instances.
	 * <!-- begin-user-doc --> <!--
     * end-user-doc -->
	 * @generated
	 */
    protected SelectDescriptionStyleItemProvider selectDescriptionStyleItemProvider;

    /**
     * This creates an adapter for a {@link org.eclipse.sirius.components.view.form.SelectDescriptionStyle}. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter createSelectDescriptionStyleAdapter() {
		if (selectDescriptionStyleItemProvider == null)
		{
			selectDescriptionStyleItemProvider = new SelectDescriptionStyleItemProvider(this);
		}

		return selectDescriptionStyleItemProvider;
	}

    /**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sirius.components.view.form.ConditionalSelectDescriptionStyle} instances.
	 * <!-- begin-user-doc
     * --> <!-- end-user-doc -->
	 * @generated
	 */
    protected ConditionalSelectDescriptionStyleItemProvider conditionalSelectDescriptionStyleItemProvider;

    /**
	 * This creates an adapter for a {@link org.eclipse.sirius.components.view.form.ConditionalSelectDescriptionStyle}.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
    @Override
    public Adapter createConditionalSelectDescriptionStyleAdapter() {
		if (conditionalSelectDescriptionStyleItemProvider == null)
		{
			conditionalSelectDescriptionStyleItemProvider = new ConditionalSelectDescriptionStyleItemProvider(this);
		}

		return conditionalSelectDescriptionStyleItemProvider;
	}

    /**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sirius.components.view.form.TextareaDescriptionStyle} instances.
	 * <!-- begin-user-doc --> <!--
     * end-user-doc -->
	 * @generated
	 */
    protected TextareaDescriptionStyleItemProvider textareaDescriptionStyleItemProvider;

    /**
     * This creates an adapter for a {@link org.eclipse.sirius.components.view.form.TextareaDescriptionStyle}. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter createTextareaDescriptionStyleAdapter() {
		if (textareaDescriptionStyleItemProvider == null)
		{
			textareaDescriptionStyleItemProvider = new TextareaDescriptionStyleItemProvider(this);
		}

		return textareaDescriptionStyleItemProvider;
	}

    /**
     * This keeps track of the one adapter used for all
     * {@link org.eclipse.sirius.components.view.form.ConditionalTextareaDescriptionStyle} instances. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    protected ConditionalTextareaDescriptionStyleItemProvider conditionalTextareaDescriptionStyleItemProvider;

    /**
	 * This creates an adapter for a {@link org.eclipse.sirius.components.view.form.ConditionalTextareaDescriptionStyle}.
	 * <!-- begin-user-doc --> <!--
     * end-user-doc -->
	 * @generated
	 */
    @Override
    public Adapter createConditionalTextareaDescriptionStyleAdapter() {
		if (conditionalTextareaDescriptionStyleItemProvider == null)
		{
			conditionalTextareaDescriptionStyleItemProvider = new ConditionalTextareaDescriptionStyleItemProvider(this);
		}

		return conditionalTextareaDescriptionStyleItemProvider;
	}

    /**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sirius.components.view.form.TextfieldDescriptionStyle} instances.
	 * <!-- begin-user-doc --> <!--
     * end-user-doc -->
	 * @generated
	 */
    protected TextfieldDescriptionStyleItemProvider textfieldDescriptionStyleItemProvider;

    /**
     * This creates an adapter for a {@link org.eclipse.sirius.components.view.form.TextfieldDescriptionStyle}. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter createTextfieldDescriptionStyleAdapter() {
		if (textfieldDescriptionStyleItemProvider == null)
		{
			textfieldDescriptionStyleItemProvider = new TextfieldDescriptionStyleItemProvider(this);
		}

		return textfieldDescriptionStyleItemProvider;
	}

    /**
     * This keeps track of the one adapter used for all
     * {@link org.eclipse.sirius.components.view.form.ConditionalTextfieldDescriptionStyle} instances. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    protected ConditionalTextfieldDescriptionStyleItemProvider conditionalTextfieldDescriptionStyleItemProvider;

    /**
	 * This creates an adapter for a {@link org.eclipse.sirius.components.view.form.ConditionalTextfieldDescriptionStyle}.
	 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
	 * @generated
	 */
    @Override
    public Adapter createConditionalTextfieldDescriptionStyleAdapter() {
		if (conditionalTextfieldDescriptionStyleItemProvider == null)
		{
			conditionalTextfieldDescriptionStyleItemProvider = new ConditionalTextfieldDescriptionStyleItemProvider(this);
		}

		return conditionalTextfieldDescriptionStyleItemProvider;
	}

    /**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sirius.components.view.form.DateTimeDescriptionStyle} instances.
	 * <!-- begin-user-doc --> <!--
     * end-user-doc -->
	 * @generated
	 */
    protected DateTimeDescriptionStyleItemProvider dateTimeDescriptionStyleItemProvider;

    /**
     * This creates an adapter for a {@link org.eclipse.sirius.components.view.form.DateTimeDescriptionStyle}. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter createDateTimeDescriptionStyleAdapter() {
		if (dateTimeDescriptionStyleItemProvider == null)
		{
			dateTimeDescriptionStyleItemProvider = new DateTimeDescriptionStyleItemProvider(this);
		}

		return dateTimeDescriptionStyleItemProvider;
	}

    /**
     * This keeps track of the one adapter used for all
     * {@link org.eclipse.sirius.components.view.form.ConditionalDateTimeDescriptionStyle} instances. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    protected ConditionalDateTimeDescriptionStyleItemProvider conditionalDateTimeDescriptionStyleItemProvider;

    /**
	 * This creates an adapter for a {@link org.eclipse.sirius.components.view.form.ConditionalDateTimeDescriptionStyle}.
	 * <!-- begin-user-doc --> <!--
     * end-user-doc -->
	 * @generated
	 */
    @Override
    public Adapter createConditionalDateTimeDescriptionStyleAdapter() {
		if (conditionalDateTimeDescriptionStyleItemProvider == null)
		{
			conditionalDateTimeDescriptionStyleItemProvider = new ConditionalDateTimeDescriptionStyleItemProvider(this);
		}

		return conditionalDateTimeDescriptionStyleItemProvider;
	}

    /**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sirius.components.view.form.ContainerBorderStyle} instances.
	 * <!-- begin-user-doc --> <!--
     * end-user-doc -->
	 * @generated
	 */
    protected ContainerBorderStyleItemProvider containerBorderStyleItemProvider;

    /**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sirius.components.view.form.ConditionalContainerBorderStyle} instances.
	 * <!-- begin-user-doc
     * --> <!-- end-user-doc -->
	 * @generated
	 */
    protected ConditionalContainerBorderStyleItemProvider conditionalContainerBorderStyleItemProvider;

    /**
     * This creates an adapter for a {@link org.eclipse.sirius.components.view.form.ContainerBorderStyle}. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter createContainerBorderStyleAdapter() {
		if (containerBorderStyleItemProvider == null)
		{
			containerBorderStyleItemProvider = new ContainerBorderStyleItemProvider(this);
		}

		return containerBorderStyleItemProvider;
	}

    /**
	 * This creates an adapter for a {@link org.eclipse.sirius.components.view.form.ConditionalContainerBorderStyle}.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
    @Override
    public Adapter createConditionalContainerBorderStyleAdapter() {
		if (conditionalContainerBorderStyleItemProvider == null)
		{
			conditionalContainerBorderStyleItemProvider = new ConditionalContainerBorderStyleItemProvider(this);
		}

		return conditionalContainerBorderStyleItemProvider;
	}

    /**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sirius.components.view.form.FormElementFor} instances.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
    protected FormElementForItemProvider formElementForItemProvider;

    /**
	 * This creates an adapter for a {@link org.eclipse.sirius.components.view.form.FormElementFor}.
	 * <!-- begin-user-doc
     * --> <!-- end-user-doc -->
	 * @generated
	 */
    @Override
    public Adapter createFormElementForAdapter() {
		if (formElementForItemProvider == null)
		{
			formElementForItemProvider = new FormElementForItemProvider(this);
		}

		return formElementForItemProvider;
	}

    /**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sirius.components.view.form.FormElementIf} instances.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
    protected FormElementIfItemProvider formElementIfItemProvider;

    /**
	 * This creates an adapter for a {@link org.eclipse.sirius.components.view.form.FormElementIf}.
	 * <!-- begin-user-doc
     * --> <!-- end-user-doc -->
	 * @generated
	 */
    @Override
    public Adapter createFormElementIfAdapter() {
		if (formElementIfItemProvider == null)
		{
			formElementIfItemProvider = new FormElementIfItemProvider(this);
		}

		return formElementIfItemProvider;
	}

    /**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
    @Override
    public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

    /**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
    @Override
    public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

    /**
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
    @Override
    public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

    /**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc --> <!--
     * end-user-doc -->
	 * @generated
	 */
    @Override
    public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

    /**
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
    @Override
    public Object adapt(Object object, Object type) {
		if (isFactoryForType(type))
		{
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter)))
			{
				return adapter;
			}
		}

		return null;
	}

    /**
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
    public List<IChildCreationExtender> getChildCreationExtenders() {
		return childCreationExtenderManager.getChildCreationExtenders();
	}

    /**
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
    @Override
    public Collection<?> getNewChildDescriptors(Object object, EditingDomain editingDomain) {
		return childCreationExtenderManager.getNewChildDescriptors(object, editingDomain);
	}

    /**
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
    @Override
    public ResourceLocator getResourceLocator() {
		return childCreationExtenderManager;
	}

    /**
	 * This adds a listener.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
    @Override
    public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

    /**
	 * This removes a listener.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
    @Override
    public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

    /**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc --> <!--
     * end-user-doc -->
	 * @generated
	 */
    @Override
    public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null)
		{
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

    /**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
    @Override
    public void dispose() {
		if (formDescriptionItemProvider != null) formDescriptionItemProvider.dispose();
		if (formVariableItemProvider != null) formVariableItemProvider.dispose();
		if (pageDescriptionItemProvider != null) pageDescriptionItemProvider.dispose();
		if (groupDescriptionItemProvider != null) groupDescriptionItemProvider.dispose();
		if (barChartDescriptionItemProvider != null) barChartDescriptionItemProvider.dispose();
		if (buttonDescriptionItemProvider != null) buttonDescriptionItemProvider.dispose();
		if (checkboxDescriptionItemProvider != null) checkboxDescriptionItemProvider.dispose();
		if (dateTimeDescriptionItemProvider != null) dateTimeDescriptionItemProvider.dispose();
		if (flexboxContainerDescriptionItemProvider != null) flexboxContainerDescriptionItemProvider.dispose();
		if (imageDescriptionItemProvider != null) imageDescriptionItemProvider.dispose();
		if (labelDescriptionItemProvider != null) labelDescriptionItemProvider.dispose();
		if (linkDescriptionItemProvider != null) linkDescriptionItemProvider.dispose();
		if (listDescriptionItemProvider != null) listDescriptionItemProvider.dispose();
		if (multiSelectDescriptionItemProvider != null) multiSelectDescriptionItemProvider.dispose();
		if (pieChartDescriptionItemProvider != null) pieChartDescriptionItemProvider.dispose();
		if (radioDescriptionItemProvider != null) radioDescriptionItemProvider.dispose();
		if (richTextDescriptionItemProvider != null) richTextDescriptionItemProvider.dispose();
		if (selectDescriptionItemProvider != null) selectDescriptionItemProvider.dispose();
		if (splitButtonDescriptionItemProvider != null) splitButtonDescriptionItemProvider.dispose();
		if (textAreaDescriptionItemProvider != null) textAreaDescriptionItemProvider.dispose();
		if (textfieldDescriptionItemProvider != null) textfieldDescriptionItemProvider.dispose();
		if (treeDescriptionItemProvider != null) treeDescriptionItemProvider.dispose();
		if (sliderDescriptionItemProvider != null) sliderDescriptionItemProvider.dispose();
		if (barChartDescriptionStyleItemProvider != null) barChartDescriptionStyleItemProvider.dispose();
		if (conditionalBarChartDescriptionStyleItemProvider != null) conditionalBarChartDescriptionStyleItemProvider.dispose();
		if (buttonDescriptionStyleItemProvider != null) buttonDescriptionStyleItemProvider.dispose();
		if (conditionalButtonDescriptionStyleItemProvider != null) conditionalButtonDescriptionStyleItemProvider.dispose();
		if (checkboxDescriptionStyleItemProvider != null) checkboxDescriptionStyleItemProvider.dispose();
		if (conditionalCheckboxDescriptionStyleItemProvider != null) conditionalCheckboxDescriptionStyleItemProvider.dispose();
		if (dateTimeDescriptionStyleItemProvider != null) dateTimeDescriptionStyleItemProvider.dispose();
		if (conditionalDateTimeDescriptionStyleItemProvider != null) conditionalDateTimeDescriptionStyleItemProvider.dispose();
		if (labelDescriptionStyleItemProvider != null) labelDescriptionStyleItemProvider.dispose();
		if (conditionalLabelDescriptionStyleItemProvider != null) conditionalLabelDescriptionStyleItemProvider.dispose();
		if (linkDescriptionStyleItemProvider != null) linkDescriptionStyleItemProvider.dispose();
		if (conditionalLinkDescriptionStyleItemProvider != null) conditionalLinkDescriptionStyleItemProvider.dispose();
		if (listDescriptionStyleItemProvider != null) listDescriptionStyleItemProvider.dispose();
		if (conditionalListDescriptionStyleItemProvider != null) conditionalListDescriptionStyleItemProvider.dispose();
		if (multiSelectDescriptionStyleItemProvider != null) multiSelectDescriptionStyleItemProvider.dispose();
		if (conditionalMultiSelectDescriptionStyleItemProvider != null) conditionalMultiSelectDescriptionStyleItemProvider.dispose();
		if (pieChartDescriptionStyleItemProvider != null) pieChartDescriptionStyleItemProvider.dispose();
		if (conditionalPieChartDescriptionStyleItemProvider != null) conditionalPieChartDescriptionStyleItemProvider.dispose();
		if (radioDescriptionStyleItemProvider != null) radioDescriptionStyleItemProvider.dispose();
		if (conditionalRadioDescriptionStyleItemProvider != null) conditionalRadioDescriptionStyleItemProvider.dispose();
		if (selectDescriptionStyleItemProvider != null) selectDescriptionStyleItemProvider.dispose();
		if (conditionalSelectDescriptionStyleItemProvider != null) conditionalSelectDescriptionStyleItemProvider.dispose();
		if (textareaDescriptionStyleItemProvider != null) textareaDescriptionStyleItemProvider.dispose();
		if (conditionalTextareaDescriptionStyleItemProvider != null) conditionalTextareaDescriptionStyleItemProvider.dispose();
		if (textfieldDescriptionStyleItemProvider != null) textfieldDescriptionStyleItemProvider.dispose();
		if (conditionalTextfieldDescriptionStyleItemProvider != null) conditionalTextfieldDescriptionStyleItemProvider.dispose();
		if (containerBorderStyleItemProvider != null) containerBorderStyleItemProvider.dispose();
		if (conditionalContainerBorderStyleItemProvider != null) conditionalContainerBorderStyleItemProvider.dispose();
		if (formElementForItemProvider != null) formElementForItemProvider.dispose();
		if (formElementIfItemProvider != null) formElementIfItemProvider.dispose();
	}

    /**
	 * A child creation extender for the {@link ViewPackage}.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
    public static class ViewChildCreationExtender implements IChildCreationExtender {
        /**
		 * The switch for creating child descriptors specific to each extended class.
		 * <!-- begin-user-doc --> <!--
         * end-user-doc -->
		 * @generated
		 */
        protected static class CreationSwitch extends ViewSwitch<Object> {
            /**
			 * The child descriptors being populated.
			 * <!-- begin-user-doc --> <!-- end-user-doc -->
			 * @generated
			 */
            protected List<Object> newChildDescriptors;

            /**
			 * The domain in which to create the children.
			 * <!-- begin-user-doc --> <!-- end-user-doc -->
			 * @generated
			 */
            protected EditingDomain editingDomain;

            /**
			 * Creates the a switch for populating child descriptors in the given domain.
			 * <!-- begin-user-doc --> <!--
             * end-user-doc -->
			 * @generated
			 */
            CreationSwitch(List<Object> newChildDescriptors, EditingDomain editingDomain) {
				this.newChildDescriptors = newChildDescriptors;
				this.editingDomain = editingDomain;
			}

            /**
             * <!-- begin-user-doc --> <!-- end-user-doc -->
             *
             * @generated NOT
             */
            @Override
            public Object caseView(View object) {
                FormDescription newFormDescription = FormFactory.eINSTANCE.createFormDescription();
                newFormDescription.setName("New Form Description");
                PageDescription pageDescription = FormFactory.eINSTANCE.createPageDescription();
                newFormDescription.getPages().add(pageDescription);
                GroupDescription groupDescription = FormFactory.eINSTANCE.createGroupDescription();
                pageDescription.getGroups().add(groupDescription);
                this.newChildDescriptors.add(this.createChildParameter(ViewPackage.Literals.VIEW__DESCRIPTIONS, newFormDescription));

                return null;
            }

            /**
			 * <!-- begin-user-doc --> <!-- end-user-doc -->
			 * @generated
			 */
            protected CommandParameter createChildParameter(Object feature, Object child) {
				return new CommandParameter(null, feature, child);
			}

        }

        /**
		 * <!-- begin-user-doc --> <!-- end-user-doc -->
		 * @generated
		 */
        @Override
        public Collection<Object> getNewChildDescriptors(Object object, EditingDomain editingDomain) {
			ArrayList<Object> result = new ArrayList<Object>();
			new CreationSwitch(result, editingDomain).doSwitch((EObject)object);
			return result;
		}

        /**
		 * <!-- begin-user-doc --> <!-- end-user-doc -->
		 * @generated
		 */
        @Override
        public ResourceLocator getResourceLocator() {
			return FormEditPlugin.INSTANCE;
		}
    }

}
