= Add support of non synchronized tables

== Problem

Currently, tables are synchronized regarding the semantic elements found in the model.
The table defines, inside its row description, what kind of elements the table handles and how they are retrieved.
So currently, whenever a compatible element is created, it is automatically added as a new row of the table.
There is no way to create a table that does not follow this mechanism. +
It is not possible to let the user choose the elements displayed as rows in the table.

== Key Result

As a specifier, I want to describe a table that is not synchronized. +
As a specifier, I want to define the drag & drop behavior that allows to add rows. +
As a end-user, I want to drag semantic elements from the model explorer and drop those elements in the table, so that it create rows accordingly to the implemented behavior.

== Solution

Sirius-web will provide a `SynchronizationPolicy` in the `TableDescription` view model level that specifier could use.
Default synchronization policy value should be `Synchronized` for compatibility reason, but new tables could be defined with `Unsynchronized`.
The table representation should react to drag and drop event in order to receive new elements during table usage.

=== Scenario : define the TableDescription

As a specifier

* Create a Table description in a view model (no semantic candidates expression should be set since it won't be used)
* Set the domain type of table rows
* Set the synchronization policy to `Unsynchronized`
* Add `DragDropTool` with some operations inside to define the behavior.

=== Scenario : play with the table

As a user

* Create the table representation
* Assuming we have a compatible element already created in the model
* Drag and drop such an element from the Explorer panel to the table representation

== No-gos
