= ADR-085 - Improve frontend selection support

== Context

Selection handling is currently managed by the `Workbench` frontend component, which is only part (although the main one) of the project edition view/page (EditProjectView).
Actions of the EditProjectView which are not part of the workbench (for example in the navbar and its menu) should also be able to read and set the selection.

== Decision

We will extract selection handling from `Workbench(Machine).tsx` into a custom hook.
This will simplify the Workbench state machine.

It will also isolate selection handling implementation and enable a lot of simplications where we used to drill down `selection` and/or `setSelection` using props.
Components which need to read/set the selection will be able to to so using:

```js
const [selection, setSelection] = useSelection();
```

Some components (notably the worbench itself) need to be able to react to selection changes.
They can do this with a `useEffect()` which reacts to changes in the selection value:

```js
const [selection] = useSelection();
useEffect(() => {
  /* handle the new selection value */
}, [selection]);
```

Components which used to get the selection and/or setSelection callback as part of their props just to pass them to their children will be simplified.

The state needed for the new hook will be created inside `EditProjectView` (the parent of the Workbench and the project navbar):

```js
const [selection, setSelection] = useState<Selection>({ entries: [] });

return (
  <SelectionContext.Provider value={{ selection, setSelection }}>
    {navbar}
    {main}
    <Snackbar />
  </SelectionContext.Provider>);
```

This makes sense because the selection is relative to a particular project/editing context.

== Status

Work in progress
