= ADR-094 - Provide better control on contextual palette's content

== Context

In View-based diagrams, the rules which define the content of the contextual palette of an element from the actual View model are hard to understand and require all sorts of workarounds in concrete modelers to get a usable behavior.

Currently, if a node or edge descriptions defines a _Label Edit_ or _Delete_ tool, these will be available on the contextual palette of instances of that description.
This is fine: it's easy to understand and control, especially with https://github.com/eclipse-sirius/sirius-components/issues/1563.

However, the rule for _Node Tool_ or _Edge Tools_ are different, hard to understand and require all sorts of workarounds in concrete modelers to get a usable behavior.
Currently, a _Node Tool_ defined in a node description _ND_ will not appear in the palette of _ND_ instances, but in the palette of elements which _can contain_ instances of _ND_.
This choice was made when _Node Tool_ were initialy designed as tools to *create new instances* of a node, so it made sense to make them available in the context(s) where those new instances can be created.
However _Node Tools_ can have an arbitrary behavior, not just for creating new instances.
In practical modelers it is often needed to create a tool that will apply some transformation on the node it is applied to.
Currently, the only way to do this is to create these tools not on the actual target but on one of its child element.
If the node does not have any child, one has to create a "dummy" child node, with an empty `semanticCandidateExpression` just for the purpose of holding the tool(s) that one want to appear in the parent's palette.

The initial reasoning and issues are similar for _Edge Tools_.
An additional issue/limitation for edges is that it currently not possible to create "single element" tools that apply to them, even though the core runtime (will) supports this with https://github.com/eclipse-sirius/sirius-components/issues/1574.

== Decision

Following a similar philosophy as in https://github.com/eclipse-sirius/sirius-components/issues/1563 we will change the View DSL to make the rules simpler and more explicit directly in the model.

We will add a new _Palette_ child element in:

- _Diagram Description_
- _Node Description_
- _Edge Description_

The palette defined inside such a View element determines which tools are available on the contextual palette of corresponding instances on a diagram.

A _Diagram Palette_ can contain one _Drop Tool_ and any number of _Node Tool_, which will be available on the contexutal palette of the diagram's background.

The _Node Palette_ and _Edge Palette_ will contain the existing _Label Edit_ and _Delete_ tools (which will be moved from their current location directly inside the Node/Edge Description).
For the _Edge Palette_ this means one label edit tool per potential label (begin, center, end).

A _Node Palette_ can contain any number of _Node Tools_ (corresponding to a `SingleClickOnDiagramElementTool` invoked on the node instance) and _Edge Tools_ (corresponding to `SingleClickOnTwoDiagramElementsTool` invoked _from_ the node instance as a source).

An _Edge Palette_ can contain any number of _Node Tools_ (corresponding to a `SingleClickOnDiagramElementTool` invoked on the edge instance) and any number of `EdgeReconnectionTool`, which are simply the `reconnectEdgeTools` previously defined directly under the _Edge Description_.

This work will require no changes on the frontend.
Change will only concern the View DSL definition, `ViewDiagramDescriptionConverter`, `ViewToolSectionsProvider` and associated classes.

== Status

Accepted.

== Consequences

- Studio makers will have an easier control on which tools appear in the palette of each element of their diagrams.
- The Papaya example modeler will need to be adapter to move the tool definitions in the appropriate element's palettes.
- In this proposed version there is no way to organise the tools in a palette in different sections.
This would certainly be possible but add more complexity to the model (e.g. add a _Tool Section_ element inside _Palette_).
