= ADR-107 - Add support for dynamic and conditional widgets in Forms

== Context

The set of widgets displayed by a _Form_ is currently hard-coded statically in the structure of the corresponding _FormDescription_.
Each _WidgetDescription_ will produce one, and only one, concrete widget when the form is rendered.

On the desktop side, EEF overcame this limitation by introducing https://eclipse.dev/sirius/doc/specifier/properties/Properties_View_Description.html#dynamic_mappings[dynamic mappings], based on two new configuration elements: `DynamicFor` and `DynamicIf`.

The core rendering algorithm of the Sirius Web Forms already implements these mechanisms to support the compatibility layer with Sirius Desktop VSMs, but they are not exposed when creating a _FormDescription_ using the View DSL.

== Decision

We will add support for _For_ and _If_ elements to the Forms DSL.
They will be named _FormElementFor_ and _FormElementIf_ in the metamodel, but presented as simply _For_ an _If_ in the UI.
In this first version, we will only support these new constructs inside _Groups_ and _FlexboxContainers_.

All these four elements (For, If, Groups, Flexbox) behave as containers for an arbitrary number of sub-elements.
To provide a common API for them, we will introduce an abstract _FormElementDescription_ type, which only contains a _name_ attribute.
Widgets (including FlexboxContainer) _and_ constructs like _For_ and _If_ are sub-types of _FormElementDescription_, but _Group_ is not.
For, If, Group and Flexbox will have a _children : FormElementDescription_ many-valued containment reference.

Except for Groups which can only occur at the root of a Page, this structure allows for arbitrary combinations of all 3 of _For_, _If_ and _Flexbox_.
It's possible to have _For_ without _If_, or with many of them; to have nested _For_ loop; _If_ outside of a _For_ loop, _If_ with an arbitrary number of sub-elements, including nested _If_, etc.

_FormElementFor_ will have two attributes:

* `iterationExpression`: an AQL expression to be evaluated when rendering the form, which should return a collection of (arbitrary) elements;
* `iterator`: a (fixed) variable name.

The semantics of the element is that it's children element will be rendered once for every element in the collection returned by `iterationExpression`, in order.
For each value _V_ returned by `iterationExpression`, all the children are rendered in a context where _V_ is bound to a variable named as specified by _iterator_.

_FormElementIf_ will have a single attribute:

* `predicateExpression`: an AQL expression to be evaluated when rendering the form, which should return a boolean.
If placed inside a _FormElementFor_ (or several nested ones), the expression has access to its (their) iterator variable.

The semantics of the element is simple: the children of the _FormElementIf_ are only rendered if the expression returned `true`.

== Status

Accepted.

== Consequences

* Any custom widget's metamodel will need to be regenerated.
This is required for the custom widget's child creation extender to be able to be created inside the new _DynamicIf_ elements.
* With this, it will become possible to express more generic and dynamic form descriptions, including the equivalent of https://github.com/eclipse-sirius/sirius-desktop/blob/master/plugins/org.eclipse.sirius.properties.defaultrules/model/properties.odesign[Sirius Desktop defaults properties rules].
* The first version if the mechanism introduced here will be generalized to allow For/If in as many places as possible (and meaningful) in the Forms DSL, notable on Groups and Pages.
Note that pages already support `semanticCandidatesExpression` which cover part of the same uses cases but is less powerful.
