= ADR-144 - Add the support for EMF models migration

== Context

We want to be able to load any model created with a previous version of Sirius Web. 

== Decision

Since models are serialized / deserialized with EMF, we will use the `ExtendedMetaData` mechanism from EMF.

== Consequences

We will extend `ExtendedMetaData` with another class  `MigrationExtendedMetaData` that will be instantiated with the current version of the model expected by Sirius Web and a list of `IMigrationParticipant`.

This class will also override the necessary methods from `BasicExtendedMetaData` that will allow us to migrate the model (like `getLocalElement`)

One important thing to consider is that BasicExtendedMetaData methods assume that the model is stored in XMl format, since we're using JSON format, we should be really cautious about using the default methods and might have to override most of them even if we don't use them all for migrating, a BasicJSonExtendedMetaData might even be needed.

The version of the last migration used on a model will be stored at the root of the JSON document on EMFJson side.

The version of a migration participant will represent when it was added to the project and will respect this structure : `ITERATION-YYYYMMDDHHMM`

For example `2024.5.0-202404221400` for a participant added on 2024-04-22 at 14h00 for the iteration 2024.5.0.

[source,java]
----
public class MigrationExtendedMetaData extends BasicExtendedMetaData {

    private final String version;

    private final List<IMigrationParticipant> migrationParticipants;

    public ViewExtendedMetaData(List<IMigrationParticipant> migrationParticipants, String version) {
        this.migrationParticipants = Objects.requireNonNull(migrationParticipants);
        this.version = Objects.requireNonNull(version);
    }

    private boolean isCandidateVersion(IMigrationParticipant migrationParticipant) {
        return migrationParticipant.getVersion().compareTo(this.version) < 0;
    }

    @Override
    public EStructuralFeature getLocalElement(EClass eClass,  String namespace, String eStructuralFeatureName) {
        EStructuralFeature structuralFeature = eClass.getEStructuralFeature(eStructuralFeatureName);
        var migrationParticipants = iMigrationParticipants.stream()
                .filter(this::isCandidateVersion)
                .sorted(Comparator.comparing(IMigrationParticipant::getVersion))
                .toList();

        for (IMigrationParticipant migrationParticipant : migrationParticipants) {
            structuralFeature = migrationParticipant.getStructuralFeature(eClass, eStructuralFeatureName);
        }

        return structuralFeature;
    }
}
----

In each method overridden, we call the corresponding method from `IMigrationParticipant` if it has a lesser version than the one used to instantiate the `MigrationExtendedMetaData`.

[source,java]
----
public interface IMigrationParticipant {

    String getVersion();

    EStructuralFeature getStructuralFeature(EClass eClass, String eStructuralFeatureName);
}
----


This is an example of implementation where this NameFeatureChangelMigrationParticipant will be used if the model version is superior to `2024.5.0-202404221400`.
If the feature name was changed from "name2" to something else, we provide the new correct value.

[source,java]
----
@Service
public class NameFeatureChangelMigrationParticipant implements IMigrationParticipant {

    private static final String PARTICIPANT_VERSION = "2024.5.0-202404221400";

    @Override
    public String getVersion() {
        return PARTICIPANT_VERSION;
    }

    @Override
    public EStructuralFeature getStructuralFeature(EClass eClass, String eStructuralFeatureName) {
        EStructuralFeature feature = null;
        if (DomainPackage.eINSTANCE.getDomain().equals(eClass)) {
            if (eStructuralFeatureName.equals("name2")) {
                feature = DomainPackage.eINSTANCE.getNamedElement_Name();
            }
        }
        return feature;
    }
}
----

== Status

Work in progress