= ADR-181 - Make Navigation Bar extension point more flexible

* GitHub Issue: [#4404](https://github.com/eclipse-sirius/sirius-web/issues/4404)

== Context

Currently, the Sirius Web frontend has an extension point that allows downstream applications to customize the navigation bar home button by changing its (round) icon.
The default implementation provides the Sirius Web logo as the image to use.

Downstream applications (e.g. SysON-based applications) may require a more flexible extension point to further customize that part of the navigation bar.

== Decision

We will remove current extension point `navigationBarIconExtensionPoint`.
We will add a new extension point `navigationBarIconExtensionPoint` through which downstream applications may provide an arbitrary React component to use as their navigation bar left-most component.

Other parts of the navigation bar ('left' and 'right' contributions) will not be impacted.

== Status

Proposed.

== Consequences

Existing downstream applications will need to update their contributed extension to fit the new extension point.