= ADR-202 - Add support for project duplication

== Context

An contextual menu action in the `projects` page is provided to duplicate an existing project.

== Decision

We will add an API to duplicate a project.

=== Frontend

A new `DuplicateProjectMenuItem` will be added.
This item should be self-contained, and will not defer its state or other requirements to its parent (see for example `RenameProjectMenuItem` or `DuplicateProjectMenuItem`).

[source, typescript]
----
export const DuplicateProjectMenuItem = ({project, onClick}: DuplicateProjectMenuItemProps) => {
  // Just ask for what you need from the project and use onClick to close the context menu once you are done.
}
----

The new item will be reused in `EditProjectNavbarContextMenu` and `ProjectActionButton`.

=== GraphQL schema

We will add a new mutation in `sirius-web.graphqls` and the corresponding input/payload.

----
extend type Mutation {
  // [...]
  duplicateProject(input: DuplicateProjectInput!): DuplicateProjectPayload!
}

input DuplicateProjectInput {
  id: ID!
  projectId: ID!
}

union DuplicateProjectPayload = ErrorPayload | DuplicateProjectSuccessPayload

type DuplicateProjectSuccessPayload {
  id: ID!
  project: Project!
}
----


=== Backend

We will create a new service in Sirius Web to duplicate a project.
This service will take care of duplicating the original project's:

- Semantic Data (including domains and dependencies)
- Representations
- Nature
- Settings

The created project should have a different ID than the original project.
The elements contained in the created project's semantic data should have different IDs than the ones in the original project.
The target objects of the representations should be adapted to target the duplicated objects (with their new ID).

Avoiding ID duplication (for project and elements) is key to avoid clashes in library contexts.

The overall behavior of this new service should be the same as a download followed by an upload of a project.
To achieve this, this work should reuse as much as possible the work that has been done to handle the upload of a project (see `ProjectImportService` as an entry point).
A refactoring of `ProjectImportService` may be necessary to extract common behavior that can be reused regardless of the source (uploaded zip file or existing project in the database).

We will also add a capability for project duplication, allowing to (de)activate it like the "rename" or "delete" feature.

Here is the technical path that will be followed:

=== Step 1

Create a new service `IProjectDuplicateService` that will sequentially call the `IProjectImportService` and the `IProjectExportService`.
This will offer a lightweight duplication feature that fully reuses the existing code.
From there, some features are still missing, such as:

* The settings are neither duplicated nor exported/imported (e.g., in Sirius Web, the `ProjectImage` setting).
* A project can contain multiple editing contexts (e.g., branches). The current implementation neither exports all these editing contexts nor provides a way to choose which branch to export.

=== Step 2

Refactor the `ProjectImportService` to use the same architecture as the export service, based on `IProjectImportParticipant` (similar to `IProjectExportParticipant`).
Each `IProjectImportParticipant` will be responsible for importing a part of the project content.
In the current implementation, two `IProjectImportParticipant` components will be created to import the semantic part and the representation part of the model.
This mechanism will then be used to import specific _settings_ (see Step 3).

=== Step 3

Contribute a new `IProjectImportParticipant` and a new `IProjectExportParticipant` to handle project images.

== Rabbit holes

None.


== Consequences



== Cutting backs

* This implementation will not handle the problem of several editing contexts for a project, the same behavior will remain: only the "main" branch will be exported and imported.
