= ADR-214 - Add the support for i18n

== Context

We have more and more users who English is not the native language.
Adding the support for internationalization could ease their use of Sirius-Web.

== State of the art

[NOTE]
====
I wrote this State of the art without knowing nothing about i18n in the frontend.
I based everything only on reading framework documentation, document making comparison between the tools.
====

Since we already are using i18n in our backend with Spring, I will only address the frontend part of the i18n.
However we have to discuss in another ADR about API to include in AQL Service to ease the support for i18n in AQL expression for View DSL.

With the variety of existing language comes issues for each specific language.
For that, the https://cldr.unicode.org/[Unicode CLDR] has gathered data about locales.
The https://icu.unicode.org/[ICU] project propose a set of C++ and Java libraries using the CLDR.
Even if ICU is for C++ and Java initially a lot of JavaScript libraries are using concept of ICU for example the syntax for plural the "ICU Message Syntax".

[NOTE]
====
I initially start to compare the three most used i18n JavaScript frameworks (https://react.i18next.com/[React i18next], https://formatjs.github.io/[react-intl (Format Js)] and https://github.com/lingui/js-lingui[Lingui Js]) but it appears that `React i18next` can do a lot of what others do.
Even if it does not use the ICU syntax at first, a module can provide its support.
Even if it bases its flow using key to reference translation in locale files (which may not be developer friendly), the ICU module seems to be able to create locale files without using key thanks to macros.
====

=== Glossary

CLDR: Common Locale Data Repository
ICU: International Components for Unicode

== Decision

We will use https://react.i18next.com/[React i18next] as the i18n JavaScript frontend framework.
To configure _React i18next_ we will add new react context in the Sirius Web application to which we will provide the `language` and the list of `namespaces` supported by the backend.

To retrieve the `language` and the list of `namespaces` we will use the following GraphQL schema:

[source,graphql]
----
query getLocale {
  viewer {
    language
    namespaces
  }
}
----

The `language` will be given by the value of the environment variable `spring.mvc.locale` given to the backend.
The list of supported `namespaces` will be discovered by the backend looking for the list of JSON file for a language in `/i18n/{language}/{namespace}.json` in the backend resource files.
The very same JSON file will be exposed to _React i18next_, thanks to a Spring controller on `/api/locales/{language}/{namespace}.json`.

=== How to

Anywhere a String is displayed in the UI we will need to define an entry in the locale file in the right namespace.
For example, if the String is in _sirius-components-core_ the namespace will be `siriusComponentsCore`, and thus, a file `siriusComponentsCore.json` will be present in the directory `/i18n/en/` of the backend resource files.

Once added to the namespace file we will be able to use it with the `useTranslation` hook.

NOTE: It also possible to use "macro" components like `Trans` or `Plural` (See https://react.i18next.com/latest/trans-component[Trans])

==== Example

In `TreeDescriptionsMenu.tsx`:

[source,jsx]
----
const TreeDescriptionsMenu = () => {
  const { t } = useTranslation('siriusWebApplication', { keyPrefix: 'workbenchViewsExplorer.view' });

  return (
    <div>
      <IconButton
          data-testid={`tree-descriptions-menu-icon`}
          title={t('title')}
          aria-label={t('title')}
          aria-controls="tree-descriptions-menu"
          aria-haspopup="true"
          ref={anchorRef}
          color="inherit"
          size="small"
          onClick={handleToggle}>
          <AccountTreeIcon color={open ? 'disabled' : 'inherit'} />
        </IconButton>
    </div>
  );
}

----

In `sirius-web/backend/sirius-web-application/src/main/resources/i18n/en/siriusWebApplication.json`
[source,json]
----
{
  "workbenchViewsExplorer": {
    "view": {
      "title": "Explorer"
    }
  }
}
----

In `sirius-web/backend/sirius-web-application/src/main/resources/i18n/fr/siriusWebApplication.json`
[source,json]
----
{
  "workbenchViewsExplorer": {
    "view": {
      "title": "Explorateur"
    }
  }
}
----

NOTE: There will be a small example of locale file using plural for the `siriusComponentsValidation` namespace.

== Consequences

All Strings shown to the user should now use the i18n framework.
Downstream project will be able to reuse that framework if they want to have a coherent application.
Any new language contributed by a downstream project will have to be kept updated along with the english translation files.
It may require to update our check in the CI to ensure that developers have not forgotten to generate or update locale files.

== Status

Accepted