/*******************************************************************************
 * Copyright (c) 2026 Obeo.
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *     Obeo - initial API and implementation
 *******************************************************************************/
package org.eclipse.sirius.components.view.provider.spec;

import java.util.Collection;

import org.eclipse.emf.common.notify.AdapterFactory;
import org.eclipse.sirius.components.view.ColorPalette;
import org.eclipse.sirius.components.view.TextStylePalette;
import org.eclipse.sirius.components.view.ViewFactory;
import org.eclipse.sirius.components.view.ViewPackage;
import org.eclipse.sirius.components.view.provider.ViewItemProvider;

/** Customization of the item provider implementation generated by EMF. */ public class ViewItemProviderSpec extends ViewItemProvider {     public ViewItemProviderSpec(AdapterFactory adapterFactory) {         super(adapterFactory);     }
    @Override
    public Object getImage(Object object) {
        return this.overlayImage(object, this.getResourceLocator().getImage("full/obj16/View.svg"));
    }

    @Override
    protected void collectNewChildDescriptors(Collection<Object> newChildDescriptors, Object object) {
        super.collectNewChildDescriptors(newChildDescriptors, object);

        ColorPalette newColorPalette = ViewFactory.eINSTANCE.createColorPalette();
        newColorPalette.setName("New Color Palette");
        newChildDescriptors.add(this.createChildParameter(ViewPackage.Literals.VIEW__COLOR_PALETTES, newColorPalette));
        TextStylePalette newTextStylePalette = ViewFactory.eINSTANCE.createTextStylePalette();
        newTextStylePalette.setName("New Text Style Palette");
        newChildDescriptors.add(this.createChildParameter(ViewPackage.Literals.VIEW__TEXT_STYLE_PALETTES, newTextStylePalette));
    }

}
