= 2026.11.0

== Key highlights

* Project templates can now declare required libraries.
These libraries are automatically selected during project creation and cannot be unselected.


== Breaking changes

- Add a new module named `sirius-web-core-domain` to extract the core reusable parts of `sirius-web-domain`.
The classes `Module`, `Window`, `Failure`, `IResult`, `Success`, and `AbstractValidatingAggregateRoot` has been moved to this new module.
Imports of these classes must be updated to:
* `org.eclipse.sirius.web.core.domain.annotations.Module`
* `org.eclipse.sirius.web.core.domain.pagination.Window`
* `org.eclipse.sirius.web.core.domain.results.Failure`
* `org.eclipse.sirius.web.core.domain.results.IResult`
* `org.eclipse.sirius.web.core.domain.results.Success`
* `org.eclipse.sirius.web.core.domain.AbstractValidatingAggregateRoot`
- Default tools are now provided only for low-code studios.
Each downstream project using programmatic APIs and the old `DefaultToolsFactory` to define its view should now define its own default tools.
- Workbench views have been reworked: they are now collapsible, and their toolbar and title bar have been merged into a single header bar.
A new component `ViewAccordion` has been introduced to capture this new design, with two new subcomponents:
* `ViewAccordionToolbar` if the view has a toolbar
* `ViewAccordionContent` for the content of the view.
Downstream projects should now reuse them to align with the new design.
- The workbench header bar (merge of the title + toolbar) now has a grayish background.
This color can be changed through the theme palette `view.background`.
Defining this color may be required.
- Classes from the library domain such as `Library`, `ILibrarySearchService`, `ILibraryCreationService` or `LibraryCreatedEvent` have been moved to the new module `sirius-web-library-domain`.
Imports of these classes must be updated to:
* `org.eclipse.sirius.web.library.domain.Library`
* `org.eclipse.sirius.web.library.domain.services.api.ILibrarySearchService`
* `org.eclipse.sirius.web.library.domain.services.api.ILibraryCreationService`
* `org.eclipse.sirius.web.library.domain.events.LibraryCreatedEvent`
- A list of required libraries must now be provided when creating a `ProjectTemplate`.


== Bug fixes

* Icon label nodes can now be moved inside free-form containers.
* Border nodes can now display their configured child and border nodes.

== New features

* Project templates can now define required libraries by namespace, name, and version.
When users create a project from such a template, the required libraries are selected automatically and cannot be unselected.


== Improvements

- Specifiers customizing the creation, deletion, edition and drop of cards will now be able to leverage the `editingContext` variable.
- Update the backend documentation and add a first schema of the lifecycle of the backend with the creation of a project.

== Deprecation warnings

- Improve the consitency of the variables used.
For that the available variables will be found in dedicated variables classes such as:
* `org.eclipse.sirius.components.representations.RepresentationVariables`
* `org.eclipse.sirius.components.core.api.variables.CoreVariables`
These variable declarations allow us to easily find all the available variables instead of having to look at various types scattered all accross the codebase.
On top of that, they are now being used for the generation of the documentation of the View DSL builders and are used to validate the execution of some behavior at runtime.
We have thus starting to deprecate the existing variable constants which will be replaced by the new ones in the dedicated variables classes.
At the moment, we have only deprecated `VariableManager.SELF` which has been replaced by `RepresentationVariables.SELF.name()` and `IEditingContext.EDITING_CONTEXT` which has been replaced by `CoreVariables.EDITING_CONTEXT.name()`.
We will not remove existing variable constants such as `VariableManager.SELF` and `IEditingContext.EDITING_CONTEXT` soon, but we will start using these new locations for the variables in our own codebase.
When we will be satisfied with the use of these new variable declarations, we will change their annotation from `@Deprecated(since = "...")` to `@Deprecated(since = "...", forRemoval = true)` and warn downstream consumers in the CHANGELOG and release notes of that version that they should migrate to the new variable declarations.
Then, we will remove the existing variable declarations in a future release.

== Technical details

* For technical details on this {product} release, including breaking changes, please refer to {changelog-url}[changelog].
