= How to use the extension points to extend the frontend

Sirius-web is an example of an application using the various sirius-component modules.
A user may want to configure certain parts of this application.
Several extension points have been provided to enable a sirius-web-based application to customize its frontend.

== How to use the tool extension point

=== The tool component

By contributing a new custom tool, you add a React component to the palette.
This component must use as props `PaletteToolComponentProps`.
To avoid inconsistency palette representation, we encourage the use of a simple icon, but by definition, you can contribute what you want as a React component.
If needed, this icon can open a modal with more complex UI.

This component can perform some GraphQL queries and mutations.
To retrieve the _editingContextId_ and the _representationId_, you can use the following code in your component:

[source,typescript]
----
const { projectId: editingContextId, representationId } = useParams<EditProjectViewParams>();
----

=== Add the extension point to the registry

To add your custom tool to the application, you have to use `ExtensionRegistry#addComponent` function with `paletteToolExtensionPoint` as `ComponentExtensionPoint`.
By doing so, your component will be added to each diagram palette, most of the time you would like to declare your tool only on certain types of diagrams or nodes.
To do this, it's up to your component to only return something according to the props data.
Only return null in other cases.

For example, to add our papaya tool, we declare the following extension point:

[source,typescript]
----
const papayaExtensionRegistry = new ExtensionRegistry();
papayaExtensionRegistry.addComponent(paletteToolExtensionPoint, {
  identifier: 'papaya_customtool',
  Component: PapayaOperationActivityLabelDetailToolContribution,
});
----

=== Specify a reference position

Depending on the tool purpose, the click coordinates may be necessary for the result action.
For example, when the tool creates a new element on the diagram.
To achieve this, we've added a new API `IDiagramInputReferencePositionProvider`.
Where it's possible to define the way the reference position must be retrieved depending on the input.

[source,java]
----
public interface IDiagramInputReferencePositionProvider {

    boolean canHandle(IInput diagramInput);

    ReferencePosition getReferencePosition(IInput diagramInput, IDiagramContext diagramContext);
}
----

For the generic tool used in sirius-component, the provider is specified in the service `GenericDiagramToolReferencePositionProvider`.

The basic case is to use the position of the pallet as a reference position.
These coordinates are available in the props `DiagramPaletteToolContributionComponentProps`.
