= Diagram representation description

This document describes attention points on how to configure the `Diagram` representation in the `View` model.

== Node tool key bindings

It is possible to specify key bindings that can be used by the user to trigger node tools.
These key bindings should be described as children of the node tool in the view model.

A key binding defines the following properties:

* `key`: the key pressed
* `ctrl`: the Ctrl modifier
* `alt`: the Alt modifier
* `meta`: the Meta modifier

A key binding needs to define at least one modifier to be executed by the application.
Note that there is no `shift` modifier: specifiers can directly specify the capitalized `key` with no modifier in the key binding (e.g. `A` instead of `a`).

Specifiers should carefully think about the key bindings they provide and how some modifiers behave on different keyboard layout and operating systems. 
For example, a key binding for `alt+o` will be captured on windows when the user presses the keys `alt` and `o`.
On macOS, another key binding for `alt+œ` should be defined to match the same key combination, because pressing `alt` and `o` prints the `œ` character.

This issue is https://github.com/mui/mui-x/pull/14220#discussion_r1720441510[not specific to Sirius Web], and is related to https://github.com/w3c/uievents/issues/377[a broader issue implied by the deprecation of the KeyboardEvent.keyCode property].

TIP: As a rule of thumb it is recommended to only use the `ctrl` modifier and alphanumeric keys to define key bindings.

The defined key bindings do not override the default browser behavior.
Specifiers should be careful to use key bindings that work along with browser shortcuts, and consider that some shortcuts are reserved by the browser and won't trigger node tools (e.g. `Ctrl+t` will always open a new tab but won't trigger any tool).

The direct edit has a higher precedence than key binding matching. 
As a result, defining a key binding without modifiers on a diagram element that supports direct edit won't work as expected, since the direct edit will always be triggered instead of the tool with the key binding.

== Selection Dialog

Any tool can declare a `Selection Dialog` that will be opened when the tool is executed.
This dialog allows the user to select zero, one or several elements from a list of candidates defined by the specifier.
The specifier can configure the dialog to allow zero, one or several selections whether the `optional` property is set to `true` and whether the `multiple` property is set to `true`.

Knowing that the specifier needs to define a bunch of expressions to configure the different labels of different aspects of the dialog.
It can also rely on default values returns by these expressions when they are not defined.

=== Title expressions

There are three expressions for the dialog title:

* Default Title Expression: Used when the dialog is opened for the first time, and also when the selection is mandatory.
* No Selection Title Expression: Used when the selection is optional and the action allowing to confirm the dialog without selection is chosen.
* With Selection Title Expression: Used when the selection is optional and the action requiring a selection is chosen.

=== Description expression

The Description expression is used to explain the purpose of the dialog to the user.

=== Action expressions

There are two actions only displayed when the dialog allows optional selection.
Each action has a label expression and a description expression:

* No Selection Action Label Expression: Used to define the label of the action allowing to confirm the dialog without selection.
* No Selection Action Description Expression: Used to define the description of the action allowing to confirm the dialog without selection.
* With Selection Action Label Expression: Used to define the label of the action making the selection mandatory.
* With Selection Action Description Expression: Used to define the description of the action making the selection mandatory.

NOTE: If the dialog is optional the specifier is able to miss the expressions related to these actions since they will not be displayed in the dialog.

=== Confirm button expressions

There are three expressions for the confirm button:

* No Selection Confirm Button Label Expression: Used when the selection is optional and the action allowing to confirm the dialog without selection is chosen.
* Selection Required Without Selection Confirm Button Label Expression: Used when the selection is mandatory, or when the action making the selection mandatory is chosen but no selection has been made.
* Selection Required With Selection Confirm Button Label Expression: Used when the selection is mandatory, or when the action making the selection mandatory is chosen and a selection has been made.

=== Status message expressions

There are three expressions for the status message:

* No Selection Action Status Message Expression: Used when the selection is optional and the action allowing to confirm the dialog without selection is chosen.
* Selection Required Without Selection Status Message Expression: Used when the dialog is optional and the action making the selection mandatory is chosen but no selection has been made.
* Selection Required With Selection Status Message Expression: Used when the selection is mandatory, or when the action making the selection mandatory is chosen and a selection has been made.
Unlike all other expressions above, this one is evaluated every time the user updates the selection.
The specifier has access to the `selectedObjectIds` variables that contains the list of selected element IDs, and can use it to update the status message accordingly.