= Add support for a query view

== Problem

Sirius Web users need a query view to execute some expressions and view the results.

== Key Result

It shall be possible to run a query against the editing context and view the result along with its type (for example to distinguish one element from a list containing only one element).

The current selection shall be usable as an entry point of the query.
An extension point on the backend shall be available to add custom Java services too.
Various interpreter shall be supported on the backend to let specifiers add custom interpreters.

This new view shall be contributed using an extension point in order to be removal by downstream projects which may not need it.

The result of the expression will only be computed when the user will ask for it.
This view will not be a synchronized representation.

=== Acceptance Criteria

- Some Cypress tests should be added to validate that the new view interacts properly with the workbench and the selection
- Backend integration tests should be added to ensure that the core parts of the execution work as expected

=== Scenario

==== A user wants to query some models

- The user open the interpreter view
- The user click on an element in the explorer or another representation like a diagram
- They start typing an expression in the interpreter view and click on a button to perform the query
- The result appears in the result viewer underneath


=== Breadboarding

- A view on the right of the workbench with a textarea to enter an expression and a viewer underneath to display the result.


=== Cutting backs

- Content assist in the interpreter.


== Rabbit holes


== No-gos