= (S) Add selected project setting tab to the URL

== Problem

When opening a project, its settings can be reached from the contextual menu of the project (in the center of the top navigation bar).

In the Sirius Web default application, the settings have 1 tab "Images" for the project-scoped custom images.
The URL looks like: `/projects/:projectId/settings`.

Downstream applications (or future versions of Sirius Web) might include additional project setting tabs through the frontend data extension point defined in `packages\sirius-web\frontend\sirius-web-application\src\views\project-settings\ProjectSettingsViewExtensionPoints.tsx`.
For an application with additional project setting tabs, it would make sense to be able to share a URL that points to a specific tab.

== Key Result

Users shall be able to share a URL that reflects the currently-selected project setting tab.

=== Acceptance Criteria

* When navigating among the project setting tabs, the URL updates to reflect the currently-selected tab.
* Reversely, when resolving such a URL, the application opens the tab specified in the URL.

== Solution

* Since all tabs are known at startup time, it is possible to check which tabs can be uniquely identified by their title.
In practice, this will often be the case because the tab title is also used as the label for the tab, and having two tabs with the same label is unlikely.
Therefore, in most cases we will be able to use the tab title to uniquely identify the tab, and the URL will remain on the shorter side and meaningful for users.
* In case of collision in the tab titles, we will rely on the tab identifier to represent the tab to be selected.
* The title or identifier of the selected tab will be appended to the URL as an additional segment in the path, e.g. `/projects/:projectId/settings/images` or `/projects/:projectId/settings/:imagesTabId`.
* When opening the project settings page, if the URL includes a tab title or identifier, then the corresponding tab is selected and opened.
Otherwise, the first tab is opened (and its title/identifier added to the URL).

=== Breadboarding

N/A

=== Cutting backs

* By using the tab title to encode in the URL which tab to open, URLs may not be backwards compatible (e.g. a tab title may change, a new tab make use the same title as a previously-existing tab).
* It would be nice for downstream applications to be able to specify the default project setting tab, but this is out of the scope of this shape.
* It would be nice for downstream applications to be able to tweak other project setting tab contributions (e.g. change the order or titles), but this is out of the scope of this shape.

== Rabbit holes

N/A

== No-gos

N/A