/*******************************************************************************
 * Copyright (c) 2026 Obeo.
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *     Obeo - initial API and implementation
 *******************************************************************************/
package org.eclipse.sirius.components.view.table.provider.spec;

import org.eclipse.emf.common.notify.AdapterFactory;
import org.eclipse.sirius.components.view.table.provider.CellLabelWidgetDescriptionItemProvider;

/** Customization of the item provider implementation generated by EMF. */ public class CellLabelWidgetDescriptionItemProviderSpec extends CellLabelWidgetDescriptionItemProvider {     public CellLabelWidgetDescriptionItemProviderSpec(AdapterFactory adapterFactory) {         super(adapterFactory);     }
    @Override
    public Object getImage(Object object) {
        return this.overlayImage(object, this.getResourceLocator().getImage("full/obj16/CellLabelWidgetDescription.svg"));
    }

}
