/*******************************************************************************
 * Copyright (c) 2026 Obeo.
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *     Obeo - initial API and implementation
 *******************************************************************************/
package org.eclipse.sirius.components.view.table.provider.spec;

import java.util.Collection;

import org.eclipse.emf.common.notify.AdapterFactory;
import org.eclipse.sirius.components.view.table.CellDescription;
import org.eclipse.sirius.components.view.table.TableFactory;
import org.eclipse.sirius.components.view.table.TablePackage;
import org.eclipse.sirius.components.view.table.provider.TableDescriptionItemProvider;

/**
 * Customization of the item provider implementation generated by EMF.
 *
 * @author lfasani
 */
public class TableDescriptionItemProviderSpec extends TableDescriptionItemProvider {
    public TableDescriptionItemProviderSpec(AdapterFactory adapterFactory) {
        super(adapterFactory);
    }

    @Override
    public Object getImage(Object object) {
        return this.overlayImage(object, this.getResourceLocator().getImage("full/obj16/TableDescription.svg"));
    }

    @Override
    protected void collectNewChildDescriptors(Collection<Object> newChildDescriptors, Object object) {
        newChildDescriptors.add(this.createChildParameter(TablePackage.Literals.TABLE_DESCRIPTION__COLUMN_DESCRIPTIONS, TableFactory.eINSTANCE.createColumnDescription()));

        newChildDescriptors.add(this.createChildParameter(TablePackage.Literals.TABLE_DESCRIPTION__ROW_DESCRIPTION, TableFactory.eINSTANCE.createRowDescription()));

        CellDescription cellDescription = TableFactory.eINSTANCE.createCellDescription();
        cellDescription.setCellWidgetDescription(TableFactory.eINSTANCE.createCellTextfieldWidgetDescription());
        newChildDescriptors.add(this.createChildParameter(TablePackage.Literals.TABLE_DESCRIPTION__CELL_DESCRIPTIONS, cellDescription));

        newChildDescriptors.add(this.createChildParameter(TablePackage.Literals.TABLE_DESCRIPTION__ROW_FILTERS, TableFactory.eINSTANCE.createRowFilterDescription()));
    }

}
