#!/bin/sh

VERSION="$1"
mvn versions:set -DgroupId=org.eclipse.sirius -DartifactId="*" -DoldVersion="*" -DnewVersion="$VERSION" -f packages/pom.xml

npm version "$VERSION"  --commit-hooks=false --git-tag-version=false --workspaces=true --include-workspace-root=true --workspaces-update=false
npm i

for app in vscode-extension integration-tests-cypress integration-tests-playwright diagram-image-server; do
  ( cd $app && \
    npm version "$VERSION"  --commit-hooks=false --git-tag-version=false --workspaces=false --include-workspace-root=false --workspaces-update=false && \
    npm install )
done
