= Add undo redo support

== Problem

Currently, a user can't undo redo actions performed on representations.


== Key Result

The user can undo/redo an action he performed on a representation (he can't undo/redo actions performed by another user).


== Solution

Pressing ctrl+z will undo the last action performed on a representation.
Pressing ctrl+y will redo the action that was previously undone.


=== Scenario

1. Given only one user working on a representation, the user can undo/redo the actions performed
- An user renames an element from "Paul" to "Bernard"
- An user press ctrl+z
- *Expected*: the element is renamed back to "Paul" and all elements that were impacted by the change also revert back to their previous state.
- An user press ctrl+y
- *Expected*: the element is renamed back to "Bernard" and all elements that were impacted by the change also revert back to their previous state.


2. Several users are working on the same representation
- An user u1 renames an element from "Paul" to "Bernard"
- An user u2 delete the element
- If An user u1 press ctrl+z
- *Expected*: nothing will change since it would create a conflict with the change from u2


- If An user u2 press ctrl+z
- *Expected*: the semantic elements are reverted back to when the element was "Bernard"

This should work regardless of the representation.

=== Scenario (serialized representation)

Serialized representation currently used in Sirius Web contains a layout part that is not contained in an EMF resource.

On an unsynchronized representation the same scenarios as above should work.

1. Several users are working on the same node 1
- An user u1 resize a node from 10*10 to 100*100
- An user u2 add sub nodes to the same node
- If An user u1 press ctrl+z
- *Expected*: the node will be not be resize to 10*10 if the sub nodes added by u2 do not fit inside, it will be resized to a default size.

2. Several users are working on the same node 2
- An user u1 move a node from 0,0 to 10,10
- An user u2 move this node from 10,10 to 20,20
- If An user u1 press ctrl+z
- *Expected*: nothing will change since it would create a conflict with the change from u2
- If An user u2 press ctrl+z
- *Expected*: the node is moved back to 10,10 and u1 can press ctrl-z to move it back to 0,0

3. Several users are working on the same node 3
- An user u1 move a node from 0,0 to 10,10
- An user u2 move this node from 10,10 to 20,20
- An user u2 press ctrl+z to move back the node to 10,10
- An user u1 move the node from 10,10 to 0,0
- If An user u2 press ctrl+y
- *Expected*: nothing will change since it would create a conflict with the change from u1

=== Cutting backs

The undo redo will revert all semantic changes at first.
Other changes likes layout on a diagram will be taken care of later.
The undo/redo stack is lost when a user closes the web page.


== Rabbit holes

Nothing identified


== No-gos

Nothing identified