= Add support for form property section layout

== Problem

A property section in a form is made of a label, a help icon and a value area.
Currently, the layout is always vertical: label and help icon are in div and the value area is below.

== Key Result

It will be possible as a specifier to choose if the layout is horizontal or vertical.

== Solution

The property section contains 

* a "label" div which includes the label and the help icon.
* a "value"div

The content of the property section is layouted with CSS flexbox.
New attributes are added on form widget styles to specify the layout.
It corresponds to CSS flexbox options:

 * flexDirection
 * labelFlex : the flex options which is a shortHand for for `flex-grow `, `flex-shrink` and  `flex-basis`
 * valueFlex : the flex options which is a shortHand for for `flex-grow `, `flex-shrink` and  `flex-basis`
 * gap

Example:
If many property sections are defined with `labelFlex='0 0 150px'`, and 'flexDirection=row', the "label" div of all the property sections will be justified.

=== Forms editor

The form editor should display the property section accordingly to the widget styles`.

The default layout in the form editor should be unchanged.

=== Scope

The change will be done to the following widgets:
* text field
* text area
* select
* multi select
* date
* checkbox
* perhaps more

=== Default details view

The default `Details` must be displayed unchanged.
In view model, when the user had a style on a widget, the default flexbox values are initialized so that the default behavior `Details` is set unchanged.

=== Breadboarding

NA

=== Cutting backs

NA

== Rabbit holes

NA

== No-gos

