<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="view" nsURI="http://www.eclipse.org/sirius-web/view" nsPrefix="view">
  <eClassifiers xsi:type="ecore:EClass" name="View">
    <eStructuralFeatures xsi:type="ecore:EReference" name="descriptions" upperBound="-1"
        eType="#//RepresentationDescription" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RepresentationDescription" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="NewRepresentationDescription"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="domainType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="titleExpression" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="aql:'New Representation'"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiagramDescription" eSuperTypes="#//RepresentationDescription">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="autoLayout" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodeDescriptions" upperBound="-1"
        eType="#//NodeDescription" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="edgeDescriptions" upperBound="-1"
        eType="#//EdgeDescription" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiagramElementDescription" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="domainType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="semanticCandidatesExpression"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="aql:self.eContents()"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="labelExpression" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="aql:self.name"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="deleteTool" eType="#//DeleteTool"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="labelEditTool" eType="#//LabelEditTool"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NodeDescription" eSuperTypes="#//DiagramElementDescription">
    <eStructuralFeatures xsi:type="ecore:EReference" name="childrenDescriptions" upperBound="-1"
        eType="#//NodeDescription" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="style" eType="#//NodeStyle"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodeTools" upperBound="-1"
        eType="#//NodeTool" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="conditionalStyles" upperBound="-1"
        eType="#//ConditionalNodeStyle" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EdgeDescription" eSuperTypes="#//DiagramElementDescription">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isDomainBasedEdge" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceNodeDescription"
        lowerBound="1" eType="#//NodeDescription"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetNodeDescription"
        lowerBound="1" eType="#//NodeDescription"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sourceNodesExpression"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetNodesExpression"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="aql:self.eCrossReferences()"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="style" eType="#//EdgeStyle"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="edgeTools" upperBound="-1"
        eType="#//EdgeTool" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="conditionalStyles" upperBound="-1"
        eType="#//ConditionalEdgeStyle" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Style" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="color" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="#E5F5F8"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="borderColor" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="#33B0C3"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fontSize" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="14"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NodeStyle" eSuperTypes="#//Style">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="listMode" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="borderRadius" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="3"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="shape" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EdgeStyle" eSuperTypes="#//Style">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lineStyle" lowerBound="1"
        eType="#//LineStyle" defaultValueLiteral="Solid"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sourceArrowStyle" lowerBound="1"
        eType="#//ArrowStyle" defaultValueLiteral="None"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetArrowStyle" lowerBound="1"
        eType="#//ArrowStyle" defaultValueLiteral="InputArrow"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ArrowStyle">
    <eLiterals name="None"/>
    <eLiterals name="OutputArrow" value="1"/>
    <eLiterals name="InputArrow" value="2"/>
    <eLiterals name="OutputClosedArrow" value="3"/>
    <eLiterals name="InputClosedArrow" value="4"/>
    <eLiterals name="OutputFillClosedArrow" value="5"/>
    <eLiterals name="InputFillClosedArrow" value="6"/>
    <eLiterals name="Diamond" value="7"/>
    <eLiterals name="FillDiamond" value="8"/>
    <eLiterals name="InputArrowWithDiamond" value="9"/>
    <eLiterals name="InputArrowWithFillDiamond" value="10"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LineStyle">
    <eLiterals name="Solid"/>
    <eLiterals name="Dash" value="1"/>
    <eLiterals name="Dot" value="2"/>
    <eLiterals name="Dash_Dot" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tool" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="Tool"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" upperBound="-1" eType="#//Operation"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LabelEditTool" eSuperTypes="#//Tool"/>
  <eClassifiers xsi:type="ecore:EClass" name="DeleteTool" eSuperTypes="#//Tool"/>
  <eClassifiers xsi:type="ecore:EClass" name="NodeTool" eSuperTypes="#//Tool"/>
  <eClassifiers xsi:type="ecore:EClass" name="EdgeTool" eSuperTypes="#//Tool"/>
  <eClassifiers xsi:type="ecore:EClass" name="Operation" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//Operation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChangeContext" eSuperTypes="#//Operation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expression" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="aql:self"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CreateInstance" eSuperTypes="#//Operation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="referenceName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="variableName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="newInstance"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SetValue" eSuperTypes="#//Operation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="featureName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valueExpression" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnsetValue" eSuperTypes="#//Operation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="featureName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="elementExpression" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeleteElement" eSuperTypes="#//Operation"/>
  <eClassifiers xsi:type="ecore:EClass" name="Conditional" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="condition" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="aql:false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConditionalNodeStyle" eSuperTypes="#//Conditional #//NodeStyle"/>
  <eClassifiers xsi:type="ecore:EClass" name="ConditionalEdgeStyle" eSuperTypes="#//Conditional #//EdgeStyle"/>
</ecore:EPackage>
