= Development Guide
Stéphane Bégaudeau <stephane.begaudeau@obeo.fr>
v1.0.1, 2018-08-09

== Environment

The following tools are necessary to manipulate the code:

* Visual Studio Code
* Yarn 1.x
* Node 9.x

In order to properly execute the code of this project, you will need to clone it on your local machine.
Use Visual Studio Code in order to open the root sirius-components folder.
Settings have been configured for Visual Studio.

=== Visual Studio Extensions

The following extensions are recommended to manipulate the code:

* Asciidoc by Joäo Pinto
* npm by egamma
* Prettier - Code formatter by Esben Petersen
* vscode-icons by Roberto Huertas

== Dependencies

To get started, you will need to install the dependencies of the project.
Use the command `yarn install` to retrieve all the dependencies which will be installed in the `node_modules` folder.

== Execute the code

If you want to execute the code with a local server providing live reloading, use `yarn start`.

To run the test, open another terminal and run `yarn test` to launch a test server which will let you re-run the test as you wish.
To execute the tests only once with code coverage, use `yarn coverage`.
Coverage reports will be generated in the coverage folder.

Finally, to build the production version of the code which can be deployed on a server, you should use `yarn build`.
If you want to build the code to deploy it at a specific path, for example `/workflow` instead of `/`, you can use the `PUBLIC_URL` environment variable in your build.
Have a look at the create-react-app documentation for additional information regarding environment variables.

== Server

The code of the project has been created to run with the Eclipse Sirius server.
To test the code with the server, starts an instance of Eclipse with Eclipse Sirius 6.0 or more.
Make sure that the Sirius Server support is included in your instance of Eclipse.
The APIs of the server are automatically routed into a proxy during development.
See the proxy settings of the file package.json to see the configuration of the proxy.