= Information Architecture Guide
Stéphane Bégaudeau <stephane.begaudeau@obeo.fr>
v1.0.0, 2018-04-13

== Introduction

The goal of this document is to determine the various concepts which will be manipulated by our application and the way we will manipulate them.

== Projects

The first concept that our users will see in the application is the concept of project.
A project is a well known concept used to encapsulate a fragment of the work realized by the users.
A project will have various appearance in our user interface depending on our goal.
Projects may be manipulated thanks to the following appearance:

* Project Summary Card, used to display a bird eye view of the project
* Project View, used to display lots of details regarding the project 

=== Project Summary Card

The project summary card is a card which can be easily reused in our application.
It will display the most relevant pieces of information regarding our project at a glance in a concise manner.
Since our users may have projects with a sizable amount of data, we cannot display any kind of raw list of the content of the project.
As a result, most of the properties displayed in this card will either be simple or computed.
For example, we can easily display the number of semantic resources but not the raw list of semantic resources.

The project summary card will show:

* The name of the project
* The number of semantic resources
* A link to navigate to the project

=== Project View

The Project View is used to display the most important details of a project.
Since this component will take quite a lot of space, we have the ability to display some large set of data (less than 1000 entries).
In order to let others reuse as much components as possible from the project, this component will be separated in multiple sub-components.

=== Project Header Card

The Project Header Card will be the hero element of a project.
It will be used to display the main characteristics of the project like its name and description.

=== Project Semantic Resources Card

This card will be used to display the list of semantic resources in the project.
For each resource, it will show the path of the resource and some of its properties.

=== Project Representations Card

This card will show the list of representations of the project
For each representation, it will display the following properties:

* The name of the representation
* The name of the representation description
* The kind of representation (table, tree, diagram...)