= Knowledge Base
Stéphane Bégaudeau <stephane.begaudeau@obeo.fr>
v1.0.0, 2018-04-11

== Introduction
This document will contain all the errors which can be encountered during the use of our application.
It will also detail the potential symptoms and how to fix these issues, if possible.

=== 4xx & 5xx Errors

Those errors will follow the conventions of the https://tools.ietf.org/html/rfc2616#section-10[HTTP specification].

=== 1000

These kind of error are produced by an unspecified error in the code of our application.
It can be produced by a server returning some invalid content to the application.
Contact your administrator and the developers of the application to let them know of this bug.

=== 1001

These error are produced when a component is in an unspecified state.
This should come from an error in the project itself.
Contact your administrator and the developers of the application to let them know of this bug.

=== 1002

This error can be caused by an issue during the rendering of the application.
Contact your administrator and the developers of the application to let them know of this bug.