= Add impact analysis before tool execution in trees

== Problem

Sirius Web allows specifiers to add an impact analysis on tools executed on diagrams, but not on tools in contextual menus of trees.
As in diagrams, some tool executions from tree contextual menus can have a significant impact on the model, and the specifier may want to warn the end user of this impact before validating the execution.

== Key Result

The specifier can declare that an impact analysis will be triggered before the execution of a tool on a tree.
When a user triggers this tool, they receive initial feedback on the changes that will occur after the tool execution.
The user can then decide whether to apply the tool or not.

=== Acceptance criteria

- In Studio, some impact analysis should be available before the execution of the tool that updates an imported library.
It should be leveraged at least in a Cypress test to validate the complete user experience.
- Backend integration tests should also be available to ensure that the core part of the behavior are working as expected.
Those tests should probably leverage the same Studio representations.


== Scenario

=== Tool execution on a representation

On a tree representation, a user executes a tool with an active impact analysis.
A modal window opens, displaying the differences in the model before and after the tool execution.
At this point, the changes from the tool execution are not persisted (and thus other users on the same representation are not notified that a tool has been triggered).
The user can now choose to apply the tool or not.

* If the user cancels the tool execution, no changes are applied.
* If the user approves the tool execution, the tool will now be executed.

It may perform changes that are not exactly the same as the ones displayed when the user triggered the display of the impact analysis.
All the users will now see the impact of the change in their representations.

== Breadboarding

A modal window similar to the one used to display impact analysis of diagram tools.

== Cutting Backs

Only tools defined in the backend will be supported in this version.
In particular, hard-coded tools in the frontend (such as _New Object_ and _New Representation_) will not support impact analysis.

== Rabbit Holes

As for diagrams, the differences displayed in the modal are:

*  the number of elements created
*  the number of elements deleted
*  the number of elements modified

== No-Gos

Other tools (e.g. from other representations) are out of the scope of this shape.