= (M) Provide a backend-only API to retrieve a diagram as PNG or SVG file

== Problem

We currently support the export of diagrams as SVG and PNG files, but only from the frontend.

However, in both cases the actual rendering work is performed by the frontend itself (using the 'html-to-image' library or custom SVG rendering code).

This makes it cumbersome to automate and use this feature in (for example) document generation workflows, as it requires running a full browser and scraping the resulting page.

== Key Result

We should provide a simple HTTP API on the backend to export a specific diagram as a PNG or SVG file.

It should be possible to invoke this API using a simple HTTP request that can be used from any other program, from a simple shell script using `curl` to tools like M2Doc.
Something like:

[source]
----
% curl -s -H "Accept: image/png"     -o diagram.png https://example.com/api/diagram-image/026c6e4d-24ad-4cf1-a349-35a66e55257b
% curl -s -H "Accept: image/svg+xml" -o diagram.svg https://example.com/api/diagram-image/026c6e4d-24ad-4cf1-a349-35a66e55257b
----

The resulting images should be as close as possible to what is actually rendered in a normal browser (Chrome being the reference).
They should include all the elements visible on the diagram and take into account all visual modifiers (e.g. hidden/faded/collapsed states).
They should _not_ include the global diagram palette, or any selection or highlight markers.

For PNG images, we will hard-code a specific resolution (probably 1920x1200, to be adapted to the actual aspect ratio of the diagram's content).

The background of the exported images (PNG or SVG) should be transparent.

This feature may require more complex deployment than is normal at the moment (e.g. a separate process), and thus should be kept optional for cases when we want to keep deployment simple.
When not present, the corresponding HTTP endpoint should still be present, but respond with code `501 Not Implem​ented`.

In the cases where the feature *is* enabled, any additional requirements in terms of deployment should be made as simple and robust as possible, and be documented.
If the solution choosen involves a separate process, the main backend should be resilient in cases the process in question is not available or not responsive in a reasonable delay; in this case it should react as mentioned above when the feature is not enabled (and log a message for ops to detect and fix the issue in a timely manner).

== Solution

TBD

=== Scenario

TBD

=== Breadboarding

No UI, we will only add a new HTTP endpoint.

=== Cutting backs

* Provide diagram metadata (name, project, target object, etc.) as additional headers in the HTTP response.
* For PNG, allow the client to request a specific resolution (up to some reasonable maximum value) with additional headers or URL parameters.
* Allow the client to request (through additional headers or URL parameters) that an "Arrange All" is performed on the diagram before it is rendered and exported.
* Embed metadata and traceability information directly into the resulting file when exporting in SVG.
Something similar to [what Sirius Desktop does](https://github.com/eclipse-sirius/sirius-desktop/blob/master/plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/internal/render/AnnotatedSVGShape.java#L31) with `diagram:semanticTargetId` attributes on SVG elements to indicate which semantic element they represent.

== Rabbit holes

TBD

== No-gos

TBD
