/*******************************************************************************
 * Copyright (c) 2021, 2026 Obeo.
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *     Obeo - initial API and implementation
 *******************************************************************************/
package org.eclipse.sirius.components.view.diagram.provider;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;
import org.eclipse.emf.common.util.ResourceLocator;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.edit.command.CommandParameter;
import org.eclipse.emf.edit.domain.EditingDomain;
import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ChildCreationExtenderManager;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IChildCreationExtender;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;
import org.eclipse.sirius.components.view.Operation;
import org.eclipse.sirius.components.view.View;
import org.eclipse.sirius.components.view.ViewPackage;
import org.eclipse.sirius.components.view.diagram.DiagramDescription;
import org.eclipse.sirius.components.view.diagram.DiagramFactory;
import org.eclipse.sirius.components.view.diagram.DiagramPackage;
import org.eclipse.sirius.components.view.diagram.util.DiagramAdapterFactory;
import org.eclipse.sirius.components.view.util.ViewSwitch;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers. The adapters generated by this
 * factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}. The adapters
 * also support Eclipse property sheets. Note that most of the adapters are shared among multiple instances. <!--
 * begin-user-doc --> <!-- end-user-doc -->
 *
 * @generated
 */
public class DiagramItemProviderAdapterFactory extends DiagramAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable, IChildCreationExtender {

    /**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc --> <!--
     * end-user-doc -->
	 * @generated
	 */
    protected ComposedAdapterFactory parentAdapterFactory;

    /**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc --> <!--
     * end-user-doc -->
	 * @generated
	 */
    protected IChangeNotifier changeNotifier = new ChangeNotifier();

    /**
	 * This helps manage the child creation extenders.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
    protected ChildCreationExtenderManager childCreationExtenderManager = new ChildCreationExtenderManager(DiagramEditPlugin.INSTANCE, DiagramPackage.eNS_URI);

    /**
     * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    protected Collection<Object> supportedTypes = new ArrayList<Object>();

    /**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sirius.components.view.diagram.DiagramDescription} instances.
	 * <!-- begin-user-doc --> <!--
     * end-user-doc -->
	 * @generated
	 */
    protected DiagramDescriptionItemProvider diagramDescriptionItemProvider;

    /**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sirius.components.view.diagram.NodeDescription} instances.
	 * <!-- begin-user-doc --> <!--
     * end-user-doc -->
	 * @generated
	 */
    protected NodeDescriptionItemProvider nodeDescriptionItemProvider;

    /**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sirius.components.view.diagram.EdgeDescription} instances.
	 * <!-- begin-user-doc --> <!--
     * end-user-doc -->
	 * @generated
	 */
    protected EdgeDescriptionItemProvider edgeDescriptionItemProvider;

    /**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sirius.components.view.diagram.ListLayoutStrategyDescription} instances.
	 * <!-- begin-user-doc
     * --> <!-- end-user-doc -->
	 * @generated
	 */
    protected ListLayoutStrategyDescriptionItemProvider listLayoutStrategyDescriptionItemProvider;

    /**
     * This keeps track of the one adapter used for all
     * {@link org.eclipse.sirius.components.view.diagram.FreeFormLayoutStrategyDescription} instances. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    protected FreeFormLayoutStrategyDescriptionItemProvider freeFormLayoutStrategyDescriptionItemProvider;

    /**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sirius.components.view.diagram.InsideLabelDescription} instances.
	 * <!-- begin-user-doc --> <!--
     * end-user-doc -->
	 * @generated
	 */
    protected InsideLabelDescriptionItemProvider insideLabelDescriptionItemProvider;

    /**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sirius.components.view.diagram.OutsideLabelDescription} instances.
	 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
	 * @generated
	 */
    protected OutsideLabelDescriptionItemProvider outsideLabelDescriptionItemProvider;

    /**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sirius.components.view.diagram.InsideLabelStyle} instances.
	 * <!-- begin-user-doc --> <!--
     * end-user-doc -->
	 * @generated
	 */
    protected InsideLabelStyleItemProvider insideLabelStyleItemProvider;

    /**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sirius.components.view.diagram.OutsideLabelStyle} instances.
	 * <!-- begin-user-doc --> <!--
     * end-user-doc -->
	 * @generated
	 */
    protected OutsideLabelStyleItemProvider outsideLabelStyleItemProvider;

    /**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sirius.components.view.diagram.ConditionalNodeStyle} instances.
	 * <!-- begin-user-doc --> <!--
     * end-user-doc -->
	 * @generated
	 */
    protected ConditionalNodeStyleItemProvider conditionalNodeStyleItemProvider;

    /**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sirius.components.view.diagram.ConditionalInsideLabelStyle} instances.
	 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
	 * @generated
	 */
    protected ConditionalInsideLabelStyleItemProvider conditionalInsideLabelStyleItemProvider;

    /**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sirius.components.view.diagram.ConditionalOutsideLabelStyle} instances.
	 * <!-- begin-user-doc
     * --> <!-- end-user-doc -->
	 * @generated
	 */
    protected ConditionalOutsideLabelStyleItemProvider conditionalOutsideLabelStyleItemProvider;

    /**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sirius.components.view.diagram.RectangularNodeStyleDescription} instances.
	 * <!-- begin-user-doc
     * --> <!-- end-user-doc -->
	 * @generated
	 */
    protected RectangularNodeStyleDescriptionItemProvider rectangularNodeStyleDescriptionItemProvider;

    /**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sirius.components.view.diagram.ImageNodeStyleDescription} instances.
	 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
	 * @generated
	 */
    protected ImageNodeStyleDescriptionItemProvider imageNodeStyleDescriptionItemProvider;

    /**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sirius.components.view.diagram.IconLabelNodeStyleDescription} instances.
	 * <!-- begin-user-doc
     * --> <!-- end-user-doc -->
	 * @generated
	 */
    protected IconLabelNodeStyleDescriptionItemProvider iconLabelNodeStyleDescriptionItemProvider;

    /**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sirius.components.view.diagram.EdgeStyle} instances.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
    protected EdgeStyleItemProvider edgeStyleItemProvider;

    /**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sirius.components.view.diagram.ConditionalEdgeStyle} instances.
	 * <!-- begin-user-doc --> <!--
     * end-user-doc -->
	 * @generated
	 */
    protected ConditionalEdgeStyleItemProvider conditionalEdgeStyleItemProvider;

    /**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sirius.components.view.diagram.DiagramPalette} instances.
	 * <!-- begin-user-doc --> <!--
     * end-user-doc -->
	 * @generated
	 */
    protected DiagramPaletteItemProvider diagramPaletteItemProvider;

    /**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sirius.components.view.diagram.NodePalette} instances.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
    protected NodePaletteItemProvider nodePaletteItemProvider;

    /**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sirius.components.view.diagram.EdgePalette} instances.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
    protected EdgePaletteItemProvider edgePaletteItemProvider;

    /**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sirius.components.view.diagram.DeleteTool} instances.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
    protected DeleteToolItemProvider deleteToolItemProvider;

    /**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sirius.components.view.diagram.DropTool} instances.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
    protected DropToolItemProvider dropToolItemProvider;

    /**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sirius.components.view.diagram.EdgeTool} instances.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
    protected EdgeToolItemProvider edgeToolItemProvider;

    /**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sirius.components.view.diagram.LabelEditTool} instances.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
    protected LabelEditToolItemProvider labelEditToolItemProvider;

    /**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sirius.components.view.diagram.NodeTool} instances.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
    protected NodeToolItemProvider nodeToolItemProvider;

    /**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sirius.components.view.diagram.SourceEdgeEndReconnectionTool} instances.
	 * <!-- begin-user-doc
     * --> <!-- end-user-doc -->
	 * @generated
	 */
    protected SourceEdgeEndReconnectionToolItemProvider sourceEdgeEndReconnectionToolItemProvider;

    /**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sirius.components.view.diagram.TargetEdgeEndReconnectionTool} instances.
	 * <!-- begin-user-doc
     * --> <!-- end-user-doc -->
	 * @generated
	 */
    protected TargetEdgeEndReconnectionToolItemProvider targetEdgeEndReconnectionToolItemProvider;

    /**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sirius.components.view.diagram.CreateView} instances.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
    protected CreateViewItemProvider createViewItemProvider;

    /**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sirius.components.view.diagram.DeleteView} instances.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
    protected DeleteViewItemProvider deleteViewItemProvider;

    /**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sirius.components.view.diagram.DiagramToolSection} instances.
	 * <!-- begin-user-doc --> <!--
     * end-user-doc -->
	 * @generated
	 */
    protected DiagramToolSectionItemProvider diagramToolSectionItemProvider;

    /**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sirius.components.view.diagram.NodeToolSection} instances.
	 * <!-- begin-user-doc --> <!--
     * end-user-doc -->
	 * @generated
	 */
    protected NodeToolSectionItemProvider nodeToolSectionItemProvider;

    /**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sirius.components.view.diagram.EdgeToolSection} instances.
	 * <!-- begin-user-doc --> <!--
     * end-user-doc -->
	 * @generated
	 */
    protected EdgeToolSectionItemProvider edgeToolSectionItemProvider;

    /**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sirius.components.view.diagram.DropNodeTool} instances.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
    protected DropNodeToolItemProvider dropNodeToolItemProvider;

    /**
	 * This constructs an instance.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
    public DiagramItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

    /**
     * This creates an adapter for a {@link org.eclipse.sirius.components.view.diagram.DiagramDescription}. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter createDiagramDescriptionAdapter() {
		if (diagramDescriptionItemProvider == null)
		{
			diagramDescriptionItemProvider = new DiagramDescriptionItemProvider(this);
		}

		return diagramDescriptionItemProvider;
	}

    /**
     * This creates an adapter for a {@link org.eclipse.sirius.components.view.diagram.NodeDescription}. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter createNodeDescriptionAdapter() {
		if (nodeDescriptionItemProvider == null)
		{
			nodeDescriptionItemProvider = new NodeDescriptionItemProvider(this);
		}

		return nodeDescriptionItemProvider;
	}

    /**
     * This creates an adapter for a {@link org.eclipse.sirius.components.view.diagram.EdgeDescription}. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter createEdgeDescriptionAdapter() {
		if (edgeDescriptionItemProvider == null)
		{
			edgeDescriptionItemProvider = new EdgeDescriptionItemProvider(this);
		}

		return edgeDescriptionItemProvider;
	}

    /**
	 * This creates an adapter for a {@link org.eclipse.sirius.components.view.diagram.ListLayoutStrategyDescription}.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
    @Override
    public Adapter createListLayoutStrategyDescriptionAdapter() {
		if (listLayoutStrategyDescriptionItemProvider == null)
		{
			listLayoutStrategyDescriptionItemProvider = new ListLayoutStrategyDescriptionItemProvider(this);
		}

		return listLayoutStrategyDescriptionItemProvider;
	}

    /**
	 * This creates an adapter for a {@link org.eclipse.sirius.components.view.diagram.FreeFormLayoutStrategyDescription}.
	 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
	 * @generated
	 */
    @Override
    public Adapter createFreeFormLayoutStrategyDescriptionAdapter() {
		if (freeFormLayoutStrategyDescriptionItemProvider == null)
		{
			freeFormLayoutStrategyDescriptionItemProvider = new FreeFormLayoutStrategyDescriptionItemProvider(this);
		}

		return freeFormLayoutStrategyDescriptionItemProvider;
	}

    /**
     * This creates an adapter for a {@link org.eclipse.sirius.components.view.diagram.InsideLabelDescription}. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter createInsideLabelDescriptionAdapter() {
		if (insideLabelDescriptionItemProvider == null)
		{
			insideLabelDescriptionItemProvider = new InsideLabelDescriptionItemProvider(this);
		}

		return insideLabelDescriptionItemProvider;
	}

    /**
     * This creates an adapter for a {@link org.eclipse.sirius.components.view.diagram.OutsideLabelDescription}. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter createOutsideLabelDescriptionAdapter() {
		if (outsideLabelDescriptionItemProvider == null)
		{
			outsideLabelDescriptionItemProvider = new OutsideLabelDescriptionItemProvider(this);
		}

		return outsideLabelDescriptionItemProvider;
	}

    /**
     * This creates an adapter for a {@link org.eclipse.sirius.components.view.diagram.InsideLabelStyle}. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter createInsideLabelStyleAdapter() {
		if (insideLabelStyleItemProvider == null)
		{
			insideLabelStyleItemProvider = new InsideLabelStyleItemProvider(this);
		}

		return insideLabelStyleItemProvider;
	}

    /**
     * This creates an adapter for a {@link org.eclipse.sirius.components.view.diagram.OutsideLabelStyle}. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter createOutsideLabelStyleAdapter() {
		if (outsideLabelStyleItemProvider == null)
		{
			outsideLabelStyleItemProvider = new OutsideLabelStyleItemProvider(this);
		}

		return outsideLabelStyleItemProvider;
	}

    /**
     * This creates an adapter for a {@link org.eclipse.sirius.components.view.diagram.ConditionalNodeStyle}. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter createConditionalNodeStyleAdapter() {
		if (conditionalNodeStyleItemProvider == null)
		{
			conditionalNodeStyleItemProvider = new ConditionalNodeStyleItemProvider(this);
		}

		return conditionalNodeStyleItemProvider;
	}

    /**
	 * This creates an adapter for a {@link org.eclipse.sirius.components.view.diagram.ConditionalInsideLabelStyle}.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
    @Override
    public Adapter createConditionalInsideLabelStyleAdapter() {
		if (conditionalInsideLabelStyleItemProvider == null)
		{
			conditionalInsideLabelStyleItemProvider = new ConditionalInsideLabelStyleItemProvider(this);
		}

		return conditionalInsideLabelStyleItemProvider;
	}

    /**
	 * This creates an adapter for a {@link org.eclipse.sirius.components.view.diagram.ConditionalOutsideLabelStyle}.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
    @Override
    public Adapter createConditionalOutsideLabelStyleAdapter() {
		if (conditionalOutsideLabelStyleItemProvider == null)
		{
			conditionalOutsideLabelStyleItemProvider = new ConditionalOutsideLabelStyleItemProvider(this);
		}

		return conditionalOutsideLabelStyleItemProvider;
	}

    /**
	 * This creates an adapter for a {@link org.eclipse.sirius.components.view.diagram.RectangularNodeStyleDescription}.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
    @Override
    public Adapter createRectangularNodeStyleDescriptionAdapter() {
		if (rectangularNodeStyleDescriptionItemProvider == null)
		{
			rectangularNodeStyleDescriptionItemProvider = new RectangularNodeStyleDescriptionItemProvider(this);
		}

		return rectangularNodeStyleDescriptionItemProvider;
	}

    /**
     * This creates an adapter for a {@link org.eclipse.sirius.components.view.diagram.ImageNodeStyleDescription}. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter createImageNodeStyleDescriptionAdapter() {
		if (imageNodeStyleDescriptionItemProvider == null)
		{
			imageNodeStyleDescriptionItemProvider = new ImageNodeStyleDescriptionItemProvider(this);
		}

		return imageNodeStyleDescriptionItemProvider;
	}

    /**
	 * This creates an adapter for a {@link org.eclipse.sirius.components.view.diagram.IconLabelNodeStyleDescription}.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
    @Override
    public Adapter createIconLabelNodeStyleDescriptionAdapter() {
		if (iconLabelNodeStyleDescriptionItemProvider == null)
		{
			iconLabelNodeStyleDescriptionItemProvider = new IconLabelNodeStyleDescriptionItemProvider(this);
		}

		return iconLabelNodeStyleDescriptionItemProvider;
	}

    /**
	 * This creates an adapter for a {@link org.eclipse.sirius.components.view.diagram.EdgeStyle}.
	 * <!-- begin-user-doc
     * --> <!-- end-user-doc -->
	 * @generated
	 */
    @Override
    public Adapter createEdgeStyleAdapter() {
		if (edgeStyleItemProvider == null)
		{
			edgeStyleItemProvider = new EdgeStyleItemProvider(this);
		}

		return edgeStyleItemProvider;
	}

    /**
     * This creates an adapter for a {@link org.eclipse.sirius.components.view.diagram.ConditionalEdgeStyle}. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter createConditionalEdgeStyleAdapter() {
		if (conditionalEdgeStyleItemProvider == null)
		{
			conditionalEdgeStyleItemProvider = new ConditionalEdgeStyleItemProvider(this);
		}

		return conditionalEdgeStyleItemProvider;
	}

    /**
     * This creates an adapter for a {@link org.eclipse.sirius.components.view.diagram.DiagramPalette}. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter createDiagramPaletteAdapter() {
		if (diagramPaletteItemProvider == null)
		{
			diagramPaletteItemProvider = new DiagramPaletteItemProvider(this);
		}

		return diagramPaletteItemProvider;
	}

    /**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sirius.components.view.diagram.GroupPalette} instances.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
    protected GroupPaletteItemProvider groupPaletteItemProvider;

    /**
     * This creates an adapter for a {@link org.eclipse.sirius.components.view.diagram.GroupPalette}. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter createGroupPaletteAdapter() {
		if (groupPaletteItemProvider == null)
		{
			groupPaletteItemProvider = new GroupPaletteItemProvider(this);
		}

		return groupPaletteItemProvider;
	}

    /**
	 * This creates an adapter for a {@link org.eclipse.sirius.components.view.diagram.NodePalette}.
	 * <!-- begin-user-doc
     * --> <!-- end-user-doc -->
	 * @generated
	 */
    @Override
    public Adapter createNodePaletteAdapter() {
		if (nodePaletteItemProvider == null)
		{
			nodePaletteItemProvider = new NodePaletteItemProvider(this);
		}

		return nodePaletteItemProvider;
	}

    /**
	 * This creates an adapter for a {@link org.eclipse.sirius.components.view.diagram.EdgePalette}.
	 * <!-- begin-user-doc
     * --> <!-- end-user-doc -->
	 * @generated
	 */
    @Override
    public Adapter createEdgePaletteAdapter() {
		if (edgePaletteItemProvider == null)
		{
			edgePaletteItemProvider = new EdgePaletteItemProvider(this);
		}

		return edgePaletteItemProvider;
	}

    /**
	 * This creates an adapter for a {@link org.eclipse.sirius.components.view.diagram.DeleteTool}.
	 * <!-- begin-user-doc
     * --> <!-- end-user-doc -->
	 * @generated
	 */
    @Override
    public Adapter createDeleteToolAdapter() {
		if (deleteToolItemProvider == null)
		{
			deleteToolItemProvider = new DeleteToolItemProvider(this);
		}

		return deleteToolItemProvider;
	}

    /**
	 * This creates an adapter for a {@link org.eclipse.sirius.components.view.diagram.DropTool}.
	 * <!-- begin-user-doc
     * --> <!-- end-user-doc -->
	 * @generated
	 */
    @Override
    public Adapter createDropToolAdapter() {
		if (dropToolItemProvider == null)
		{
			dropToolItemProvider = new DropToolItemProvider(this);
		}

		return dropToolItemProvider;
	}

    /**
	 * This creates an adapter for a {@link org.eclipse.sirius.components.view.diagram.EdgeTool}.
	 * <!-- begin-user-doc
     * --> <!-- end-user-doc -->
	 * @generated
	 */
    @Override
    public Adapter createEdgeToolAdapter() {
		if (edgeToolItemProvider == null)
		{
			edgeToolItemProvider = new EdgeToolItemProvider(this);
		}

		return edgeToolItemProvider;
	}

    /**
     * This creates an adapter for a {@link org.eclipse.sirius.components.view.diagram.LabelEditTool}. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter createLabelEditToolAdapter() {
		if (labelEditToolItemProvider == null)
		{
			labelEditToolItemProvider = new LabelEditToolItemProvider(this);
		}

		return labelEditToolItemProvider;
	}

    /**
	 * This creates an adapter for a {@link org.eclipse.sirius.components.view.diagram.NodeTool}.
	 * <!-- begin-user-doc
     * --> <!-- end-user-doc -->
	 * @generated
	 */
    @Override
    public Adapter createNodeToolAdapter() {
		if (nodeToolItemProvider == null)
		{
			nodeToolItemProvider = new NodeToolItemProvider(this);
		}

		return nodeToolItemProvider;
	}

    /**
	 * This creates an adapter for a {@link org.eclipse.sirius.components.view.diagram.SourceEdgeEndReconnectionTool}.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
    @Override
    public Adapter createSourceEdgeEndReconnectionToolAdapter() {
		if (sourceEdgeEndReconnectionToolItemProvider == null)
		{
			sourceEdgeEndReconnectionToolItemProvider = new SourceEdgeEndReconnectionToolItemProvider(this);
		}

		return sourceEdgeEndReconnectionToolItemProvider;
	}

    /**
	 * This creates an adapter for a {@link org.eclipse.sirius.components.view.diagram.TargetEdgeEndReconnectionTool}.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
    @Override
    public Adapter createTargetEdgeEndReconnectionToolAdapter() {
		if (targetEdgeEndReconnectionToolItemProvider == null)
		{
			targetEdgeEndReconnectionToolItemProvider = new TargetEdgeEndReconnectionToolItemProvider(this);
		}

		return targetEdgeEndReconnectionToolItemProvider;
	}

    /**
	 * This creates an adapter for a {@link org.eclipse.sirius.components.view.diagram.CreateView}.
	 * <!-- begin-user-doc
     * --> <!-- end-user-doc -->
	 * @generated
	 */
    @Override
    public Adapter createCreateViewAdapter() {
		if (createViewItemProvider == null)
		{
			createViewItemProvider = new CreateViewItemProvider(this);
		}

		return createViewItemProvider;
	}

    /**
	 * This creates an adapter for a {@link org.eclipse.sirius.components.view.diagram.DeleteView}.
	 * <!-- begin-user-doc
     * --> <!-- end-user-doc -->
	 * @generated
	 */
    @Override
    public Adapter createDeleteViewAdapter() {
		if (deleteViewItemProvider == null)
		{
			deleteViewItemProvider = new DeleteViewItemProvider(this);
		}

		return deleteViewItemProvider;
	}

    /**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sirius.components.view.diagram.SelectionDialogDescription} instances.
	 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
	 * @generated
	 */
    protected SelectionDialogDescriptionItemProvider selectionDialogDescriptionItemProvider;

    /**
     * This creates an adapter for a {@link org.eclipse.sirius.components.view.diagram.SelectionDialogDescription}. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter createSelectionDialogDescriptionAdapter() {
		if (selectionDialogDescriptionItemProvider == null)
		{
			selectionDialogDescriptionItemProvider = new SelectionDialogDescriptionItemProvider(this);
		}

		return selectionDialogDescriptionItemProvider;
	}

    /**
     * This creates an adapter for a {@link org.eclipse.sirius.components.view.diagram.DiagramToolSection}. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter createDiagramToolSectionAdapter() {
		if (diagramToolSectionItemProvider == null)
		{
			diagramToolSectionItemProvider = new DiagramToolSectionItemProvider(this);
		}

		return diagramToolSectionItemProvider;
	}

    /**
     * This creates an adapter for a {@link org.eclipse.sirius.components.view.diagram.NodeToolSection}. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter createNodeToolSectionAdapter() {
		if (nodeToolSectionItemProvider == null)
		{
			nodeToolSectionItemProvider = new NodeToolSectionItemProvider(this);
		}

		return nodeToolSectionItemProvider;
	}

    /**
     * This creates an adapter for a {@link org.eclipse.sirius.components.view.diagram.EdgeToolSection}. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter createEdgeToolSectionAdapter() {
		if (edgeToolSectionItemProvider == null)
		{
			edgeToolSectionItemProvider = new EdgeToolSectionItemProvider(this);
		}

		return edgeToolSectionItemProvider;
	}

    /**
     * This creates an adapter for a {@link org.eclipse.sirius.components.view.diagram.DropNodeTool}. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter createDropNodeToolAdapter() {
		if (dropNodeToolItemProvider == null)
		{
			dropNodeToolItemProvider = new DropNodeToolItemProvider(this);
		}

		return dropNodeToolItemProvider;
	}

    /**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sirius.components.view.diagram.SelectionDialogTreeDescription} instances.
	 * <!-- begin-user-doc
     * --> <!-- end-user-doc -->
	 * @generated
	 */
    protected SelectionDialogTreeDescriptionItemProvider selectionDialogTreeDescriptionItemProvider;

    /**
	 * This creates an adapter for a {@link org.eclipse.sirius.components.view.diagram.SelectionDialogTreeDescription}.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
    @Override
    public Adapter createSelectionDialogTreeDescriptionAdapter() {
		if (selectionDialogTreeDescriptionItemProvider == null)
		{
			selectionDialogTreeDescriptionItemProvider = new SelectionDialogTreeDescriptionItemProvider(this);
		}

		return selectionDialogTreeDescriptionItemProvider;
	}

    /**
	 * This keeps track of the one adapter used for all {@link org.eclipse.sirius.components.view.diagram.Action} instances.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
    protected ActionItemProvider actionItemProvider;

    /**
	 * This creates an adapter for a {@link org.eclipse.sirius.components.view.diagram.Action}.
	 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
	 * @generated
	 */
    @Override
    public Adapter createActionAdapter() {
		if (actionItemProvider == null)
		{
			actionItemProvider = new ActionItemProvider(this);
		}

		return actionItemProvider;
	}

    /**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
    @Override
    public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

    /**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
    @Override
    public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

    /**
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
    @Override
    public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

    /**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc --> <!--
     * end-user-doc -->
	 * @generated
	 */
    @Override
    public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

    /**
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
    @Override
    public Object adapt(Object object, Object type) {
		if (isFactoryForType(type))
		{
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter)))
			{
				return adapter;
			}
		}

		return null;
	}

    /**
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
    public List<IChildCreationExtender> getChildCreationExtenders() {
		return childCreationExtenderManager.getChildCreationExtenders();
	}

    /**
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
    @Override
    public Collection<?> getNewChildDescriptors(Object object, EditingDomain editingDomain) {
		return childCreationExtenderManager.getNewChildDescriptors(object, editingDomain);
	}

    /**
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
    @Override
    public ResourceLocator getResourceLocator() {
		return childCreationExtenderManager;
	}

    /**
	 * This adds a listener.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
    @Override
    public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

    /**
	 * This removes a listener.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
    @Override
    public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

    /**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc --> <!--
     * end-user-doc -->
	 * @generated
	 */
    @Override
    public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null)
		{
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

    /**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
    @Override
    public void dispose() {
		if (diagramDescriptionItemProvider != null) diagramDescriptionItemProvider.dispose();
		if (nodeDescriptionItemProvider != null) nodeDescriptionItemProvider.dispose();
		if (edgeDescriptionItemProvider != null) edgeDescriptionItemProvider.dispose();
		if (listLayoutStrategyDescriptionItemProvider != null) listLayoutStrategyDescriptionItemProvider.dispose();
		if (freeFormLayoutStrategyDescriptionItemProvider != null) freeFormLayoutStrategyDescriptionItemProvider.dispose();
		if (insideLabelDescriptionItemProvider != null) insideLabelDescriptionItemProvider.dispose();
		if (outsideLabelDescriptionItemProvider != null) outsideLabelDescriptionItemProvider.dispose();
		if (insideLabelStyleItemProvider != null) insideLabelStyleItemProvider.dispose();
		if (outsideLabelStyleItemProvider != null) outsideLabelStyleItemProvider.dispose();
		if (conditionalNodeStyleItemProvider != null) conditionalNodeStyleItemProvider.dispose();
		if (conditionalInsideLabelStyleItemProvider != null) conditionalInsideLabelStyleItemProvider.dispose();
		if (conditionalOutsideLabelStyleItemProvider != null) conditionalOutsideLabelStyleItemProvider.dispose();
		if (rectangularNodeStyleDescriptionItemProvider != null) rectangularNodeStyleDescriptionItemProvider.dispose();
		if (imageNodeStyleDescriptionItemProvider != null) imageNodeStyleDescriptionItemProvider.dispose();
		if (iconLabelNodeStyleDescriptionItemProvider != null) iconLabelNodeStyleDescriptionItemProvider.dispose();
		if (edgeStyleItemProvider != null) edgeStyleItemProvider.dispose();
		if (conditionalEdgeStyleItemProvider != null) conditionalEdgeStyleItemProvider.dispose();
		if (diagramPaletteItemProvider != null) diagramPaletteItemProvider.dispose();
		if (groupPaletteItemProvider != null) groupPaletteItemProvider.dispose();
		if (nodePaletteItemProvider != null) nodePaletteItemProvider.dispose();
		if (edgePaletteItemProvider != null) edgePaletteItemProvider.dispose();
		if (deleteToolItemProvider != null) deleteToolItemProvider.dispose();
		if (dropToolItemProvider != null) dropToolItemProvider.dispose();
		if (edgeToolItemProvider != null) edgeToolItemProvider.dispose();
		if (labelEditToolItemProvider != null) labelEditToolItemProvider.dispose();
		if (nodeToolItemProvider != null) nodeToolItemProvider.dispose();
		if (sourceEdgeEndReconnectionToolItemProvider != null) sourceEdgeEndReconnectionToolItemProvider.dispose();
		if (targetEdgeEndReconnectionToolItemProvider != null) targetEdgeEndReconnectionToolItemProvider.dispose();
		if (createViewItemProvider != null) createViewItemProvider.dispose();
		if (deleteViewItemProvider != null) deleteViewItemProvider.dispose();
		if (selectionDialogDescriptionItemProvider != null) selectionDialogDescriptionItemProvider.dispose();
		if (diagramToolSectionItemProvider != null) diagramToolSectionItemProvider.dispose();
		if (nodeToolSectionItemProvider != null) nodeToolSectionItemProvider.dispose();
		if (edgeToolSectionItemProvider != null) edgeToolSectionItemProvider.dispose();
		if (dropNodeToolItemProvider != null) dropNodeToolItemProvider.dispose();
		if (selectionDialogTreeDescriptionItemProvider != null) selectionDialogTreeDescriptionItemProvider.dispose();
		if (actionItemProvider != null) actionItemProvider.dispose();
	}

    /**
	 * A child creation extender for the {@link ViewPackage}.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
    public static class ViewChildCreationExtender implements IChildCreationExtender {

        /**
		 * <!-- begin-user-doc --> <!-- end-user-doc -->
		 * @generated
		 */
        @Override
        public Collection<Object> getNewChildDescriptors(Object object, EditingDomain editingDomain) {
			ArrayList<Object> result = new ArrayList<Object>();
			new CreationSwitch(result, editingDomain).doSwitch((EObject)object);
			return result;
		}

        /**
		 * <!-- begin-user-doc --> <!-- end-user-doc -->
		 * @generated
		 */
        @Override
        public ResourceLocator getResourceLocator() {
			return DiagramEditPlugin.INSTANCE;
		}

        /**
		 * The switch for creating child descriptors specific to each extended class.
		 * <!-- begin-user-doc --> <!--
         * end-user-doc -->
		 * @generated
		 */
        protected static class CreationSwitch extends ViewSwitch<Object> {

            /**
			 * The child descriptors being populated.
			 * <!-- begin-user-doc --> <!-- end-user-doc -->
			 * @generated
			 */
            protected List<Object> newChildDescriptors;

            /**
			 * The domain in which to create the children.
			 * <!-- begin-user-doc --> <!-- end-user-doc -->
			 * @generated
			 */
            protected EditingDomain editingDomain;

            /**
			 * Creates the a switch for populating child descriptors in the given domain.
			 * <!-- begin-user-doc --> <!--
             * end-user-doc -->
			 * @generated
			 */
            CreationSwitch(List<Object> newChildDescriptors, EditingDomain editingDomain) {
				this.newChildDescriptors = newChildDescriptors;
				this.editingDomain = editingDomain;
			}

            /**
             * <!-- begin-user-doc --> <!-- end-user-doc -->
             *
             * @generated NOT
             */
            @Override
            public Object caseView(View object) {
                DiagramDescription newDiagramDescription = DiagramFactory.eINSTANCE.createDiagramDescription();
                newDiagramDescription.setName("New Diagram Description");
                newDiagramDescription.setPalette(new DefaultToolsFactory().createDefaultDiagramPalette());
                this.newChildDescriptors.add(this.createChildParameter(ViewPackage.Literals.VIEW__DESCRIPTIONS, newDiagramDescription));

                return null;
            }

            /**
			 * <!-- begin-user-doc --> <!-- end-user-doc -->
			 * @generated
			 */
            @Override
            public Object caseOperation(Operation object) {
				newChildDescriptors.add
					(createChildParameter
						(ViewPackage.Literals.OPERATION__CHILDREN,
						 DiagramFactory.eINSTANCE.createCreateView()));

				newChildDescriptors.add
					(createChildParameter
						(ViewPackage.Literals.OPERATION__CHILDREN,
						 DiagramFactory.eINSTANCE.createDeleteView()));

				return null;
			}

            /**
			 * <!-- begin-user-doc --> <!-- end-user-doc -->
			 * @generated
			 */
            protected CommandParameter createChildParameter(Object feature, Object child) {
				return new CommandParameter(null, feature, child);
			}

        }
    }

}
