/*******************************************************************************
 * Copyright (c) 2026 Obeo.
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *     Obeo - initial API and implementation
 *******************************************************************************/
package org.eclipse.sirius.components.view.widget.reference.provider.spec;

import java.util.Collection;

import org.eclipse.emf.common.notify.AdapterFactory;
import org.eclipse.sirius.components.view.ViewFactory;
import org.eclipse.sirius.components.view.widget.reference.ReferencePackage;
import org.eclipse.sirius.components.view.widget.reference.provider.ReferenceWidgetCreateButtonDescriptionItemProvider;

/**
 * Customization of the item provider implementation generated by EMF.
 *
 * @author tgiraudet
 */
public class ReferenceWidgetCreateButtonDescriptionItemProviderSpec extends ReferenceWidgetCreateButtonDescriptionItemProvider {

    public ReferenceWidgetCreateButtonDescriptionItemProviderSpec(AdapterFactory adapterFactory) {
        super(adapterFactory);
    }

    @Override
    public Object getImage(Object object) {
        return this.overlayImage(object, this.getResourceLocator().getImage("full/obj16/ReferenceWidgetCreateButtonDescription.svg"));
    }

    @Override
    protected void collectNewChildDescriptors(Collection<Object> newChildDescriptors, Object object) {
        newChildDescriptors.add(this.createChildParameter(ReferencePackage.Literals.REFERENCE_WIDGET_CREATE_BUTTON_DESCRIPTION__BODY, ViewFactory.eINSTANCE.createChangeContext()));
        newChildDescriptors.add(this.createChildParameter(ReferencePackage.Literals.REFERENCE_WIDGET_CREATE_BUTTON_DESCRIPTION__BODY, ViewFactory.eINSTANCE.createCreateInstance()));
        newChildDescriptors.add(this.createChildParameter(ReferencePackage.Literals.REFERENCE_WIDGET_CREATE_BUTTON_DESCRIPTION__BODY, ViewFactory.eINSTANCE.createSetValue()));
        newChildDescriptors.add(this.createChildParameter(ReferencePackage.Literals.REFERENCE_WIDGET_CREATE_BUTTON_DESCRIPTION__BODY, ViewFactory.eINSTANCE.createUnsetValue()));
        newChildDescriptors.add(this.createChildParameter(ReferencePackage.Literals.REFERENCE_WIDGET_CREATE_BUTTON_DESCRIPTION__BODY, ViewFactory.eINSTANCE.createDeleteElement()));
    }

}
