/*******************************************************************************
 * Copyright (c) 2026 Obeo.
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *     Obeo - initial API and implementation
 *******************************************************************************/
package org.eclipse.sirius.components.view.deck.provider.spec;

import java.util.Collection;

import org.eclipse.emf.common.notify.AdapterFactory;
import org.eclipse.sirius.components.view.deck.DeckFactory;
import org.eclipse.sirius.components.view.deck.DeckPackage;
import org.eclipse.sirius.components.view.deck.provider.DeckElementDescriptionItemProvider;

/**
 * Customization of the item provider implementation generated by EMF.
 *
 * @author lfasani
 */
public class DeckElementDescriptionItemProviderSpec extends DeckElementDescriptionItemProvider {
    public DeckElementDescriptionItemProviderSpec(AdapterFactory adapterFactory) {
        super(adapterFactory);
    }

    @Override
    protected void collectNewChildDescriptors(Collection<Object> newChildDescriptors, Object object) {
        super.collectNewChildDescriptors(newChildDescriptors, object);
        newChildDescriptors.add(this.createChildParameter(DeckPackage.Literals.DECK_ELEMENT_DESCRIPTION__STYLE, DeckFactory.eINSTANCE.createDeckElementDescriptionStyle()));
        newChildDescriptors.add(this.createChildParameter(DeckPackage.Literals.DECK_ELEMENT_DESCRIPTION__CONDITIONAL_STYLES, DeckFactory.eINSTANCE.createConditionalDeckElementDescriptionStyle()));
    }

    @Override
    public String getCreateChildText(Object owner, Object feature, Object child, Collection<?> selection) {
        return super.getCreateChildText(owner, feature, child, selection);
    }
}
